### ISSUE TITLE
Huge discrepancies between GCP provided CO2 and LUT calculations

### ISSUE THREAD

**Issue by tyrzong** [cloud-carbon-footprint/cloud-carbon-footprint#1016]
We are comparing GCP provided CO2 exports to those calculated using Lookup table values and see very large discrepancies that appear random between regions.
 
We are doing this in BigQuery using SQL/joins between the LUT and billing data. We narrowed it down to specific line items and don’t see any issues or duplicates. The LUT method appears to always provide much higher numbers.
 
Has anyone tried this already?

**Comment by 4upz** [comment]
Hey @tyrzong thanks for reaching out about this issue. I'd be curious to know what type of discrepancy you're seeing. Would you be able to provide an example (with any sensitive data removed) of suspicious line items?

We also have a similar issue that exists in which we're looking into resolving LUT differences from the main app's estimations. Perhaps you can see if issue #839 matches your problem, and provide additional context there. Otherwise, happy to continue the conversation here.

**Comment by tyrzong** [comment]
Hi @4upz, thank you for responding. I don't think I can share any data since everything we're working with is sensitive. I did see that there's is an update to the LUT featuere which standarized the usageUnits. Looking at our billing data, some of the units are different than the standard unit that the LUT uses, which I suspect could cause the discrepancy. I'm working on standarizing the usage unit in our billing data to match the LUT and will update if that fixes the issue.

**Comment by 4upz** [comment]
@tyrzong No worries at all! We realize how sensitive cost/emissions data can be for organizations.

Definitely check out the updates for standardizing LUT units, as it aims to help fix the issue with LUT outputs being relative to the usage units that are given as inputs -- leading to some inaccurate estimates due to them not being the appropriate units that we use for calculations. It seems this was most common for GCP and may affect your calculations as well. You can find more background in this [discussion group](https://groups.google.com/g/cloud-carbon-footprint/c/xfXD0s_THYg/m/G0OB9qJZBAAJ) that it originated from.

I'm going to close this issue for now since there are no actionable steps for us to take at this time, but feel free to update us on whether that improves some of the discrepancies you were seeing. Happy to reopen if the issue persists!
