### ISSUE TITLE
Review request for a ComputeEstimator usage

### ISSUE THREAD

**Issue by abeggchr** [cloud-carbon-footprint/cloud-carbon-footprint#1038]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Question

I am uncertain, if I use the `ComputeEstimator` correctly. I am looking for a review and feedback regarding my calculations.

### Background

* I am trying to learn how the cloud carbon footprint tools works.
* In order to do that, I created a small test comparing a cloud with an on-prem setup.
* To calculate the power consumption of the cloud setup, I use the `ComputeEstimator` of cloud carbon footprint tool and feed it with artificial data (not gathered from the cloud provider).
* The cloud scenario consists of 12 Azure "D8s v4" VMs running on 50% utilization during 1 hour.
* The estimation currently returns around 90kWh. My gut feeling says, that this is quite low. So I suspect that there's an error in my calculation.

### To Reproduce

The calculation logic is in https://github.com/abeggchr/cloud-vs-premise/blob/master/comparison.test.ts - and can probably be reviewed without checking out.

Nevertheless, here's a link to my repository:

```sh
$ git clone https://github.com/abeggchr/cloud-vs-premise.git
$ npm install
$ npm run test
```

### Scope

* only the calculation of the cloud scenario is in scope
* the validity of the comparison to an on-prem scenario is currently out of scope

**Comment by 4upz** [comment]
Hi @abeggchr, sorry for the delay in getting back to you on this! We appreciate you taking the time in trying out CCF and diving into how our estimations are done. I got a chance to review your code and estimation result.

First, 90 kWh would actually be **quite high** for only an hour of usage -- even for 12 VM instances. When running your code, I saw 0.09 kWh (0.08847524025000002 kWh when not rounded). This is more within the expected magnitude, as you'll find that most comparable compute instances with similar utilization hardly hit a full kWh within a single day.

You're mostly using the ComputeEstimator correctly! There were just a few minor issues in your code where this number can actually **be smaller** when fixed. I noticed the following:

- Your Min and Max watts constants need to be switched. The `minWatts` is assigned to the`getMaxWatts` function and vice versa (https://github.com/abeggchr/cloud-vs-premise/blob/master/comparison.test.ts#L46-L47)
- The CPU utilization should be a whole number, as the `estimate` function will convert it into a decimal percentage for you when running the energy estimation formula. Therefore, 50% utilization should be  passed as`50` instead of `0.5` (https://github.com/abeggchr/cloud-vs-premise/blob/master/comparison.test.ts#L53)

In making these changes, you should get approximately 0.05 kWh for 12 Azure "D8s v4" instances. Once you apply the [MemoryEstimator](https://www.cloudcarbonfootprint.org/docs/methodology#applying-the-coefficient), which calculates additional energy associated with the compute instances, this number will slightly increase. However, just know that these are still within a reasonable magnitude of what you'd expect for just a small window of usage. As you run these machines for longer hours across several days/weeks/months upon typical usage -- that's when you'll see the number grow into a larger footprint.

Hope that helps! I'll close this issue since there are no additional actions on our end, but happy to keep the conversation going if you have additional thoughts/questions!

**Comment by abeggchr** [comment]
Thanks a lot for the review @4upz
I updated my code and it estimates 0.035 kWh now (for compute only).
I'll get back to you should further questions arise, thx for the offer.

**Comment by abeggchr** [comment]
Hi @4upz 

I enhanced the [test](https://github.com/abeggchr/cloud-vs-premise/blob/master/comparison.test.ts ) with the estimators for storage, network, memory and embodied emissions. 

The scenario is unchanged:
```
 * - 12 Azure D8s v4 VMs
 * - 8 vCPU / 32 GB
 * - in Switzerland North
 * - 50% utilization
 * - 256GB SSD storage
 * - running 1h
 * - causing 1gb Azure-internal traffic per hour
```

The result is logged to the console. That's what the test currently calculates:

| index      | kWh     | percentage |
| ---------- |:-------:| ----------:|
| compute     | '0.280' | '5%'    |
| ssdStorage  | '0.004' | '0%'    |
| network     | '0.001' | '0%'    |
| memory      | '0.178' | '3%'    |
| embodiedEmission | '5.510' | '92%'    |

|     (index)      | CO2eq [g] | percentage |
| ---------- |:-------:| ----------:|
|     compute      |  '3.22'   |    '5%'    |
|    ssdStorage    |  '0.05'   |    '0%'    |
|     network      |  '0.01'   |    '0%'    |
|      memory      |  '2.05'   |    '3%'    |
| embodiedEmission |  '63.48'  |   '92%'    |

Questions (ordered by priority):
- Are the storage, network, memory and embodiedEmissions estimators used correctly?
- Is it correct (or commonly observable), that embodiedEmissions make up more than 90% of all emissions?
- The Swiss grid had an emission factor of ~150gCO2eq/kWh in 2022 (according to electricitymap). On the other side Azure in Switzerland has an emission factor of ~11gCO2eq/kWh (according to the cloud carbon footprint tool). There's a significant difference. What is the source of this ~11gCO2eq/kWh emission factor for Azure in Switzerland? Do you know how such a low emission factor, compared to the grid in the country, is achieved?
- For the compute estimator, is it correct to multiply the `hours` with the number of `vcpus` on line [59](https://github.com/abeggchr/cloud-vs-premise/blob/5c373abd659fefbd9f03acce27b347eb55958661/comparison.test.ts#L59). In the previous version, I only used the `hours`.
- `memory` and `compute` emissions are roughly in the same order of magnitude. Depending on the utilization, one of them is higher than the other. Is this comparable to other (real life) projects? 
- For the embodiedEmissions estimator, is it correct to multiply the `embodiedEmissions` of a single VM with the `replicationFactor` on line [128](https://github.com/abeggchr/cloud-vs-premise/blob/5c373abd659fefbd9f03acce27b347eb55958661/comparison.test.ts#L128). Why is the replication factor ignored by the `EmbodiedEmissionsEstimator`?
- For the embodiedEmissions estimator, on line [138](https://github.com/abeggchr/cloud-vs-premise/blob/5c373abd659fefbd9f03acce27b347eb55958661/comparison.test.ts#L138), to get the kWh based on CO2, the emission factor of the cloud data center is used. Is this correct from a methodological point of view? I am wondering, because the hardware is not produced with this emission factor but rather a way higher emission factor.

I look forward to clarify my questions. Thanks a lot in advance!

**Comment by abeggchr** [comment]
@4upz can you please let me know quickly that you received the previous comment so that I do not have to bother you on other channels?

**Comment by 4upz** [comment]
Sorry @abeggchr, just saw your comment. I will give it review and answer your questions shortly! 😃

**Comment by 4upz** [comment]
Hi @abeggchr thanks for your patience and apologies for the time it took to return to this. I've been able to review your updates and here are the answers to your questions:

- > Are the storage, network, memory and embodiedEmissions estimators used correctly?

    - Your usage of the storage and other estimators are correct, but I recommend revisiting your conversion of the gigabyte amount to terabyte hours on line 72. We have some helper functions exported from the the @cloud-carbon-footprint/common package that are handy for this such as `convertGigaBytesToTerabyteHours`. You may want to explore these helpers and see where it can be applied within your code to keep the conversions consistent with how CCF would apply them. One thing to note about storage is that we do prioritize allocation over utilization. So it may be better to have the estimator calculate for a day's worth of usage, and then divide that result by 24 to get the usage for an hour. Lastly, one thing I wanted to call our about memory is that you want to double-check the usage your passing is represented in GigabyteHours.
    
- > Is it correct (or commonly observable), that embodiedEmissions make up more than 90% of all emissions?
    - It is not common. In this case, it would make sense as you are estimating a tiny slice of usage (1 hr) and comparing it against the relative associated embodied emissions which usually encompasses the entire lifecycle of the machine. This ratio will decrease as the usage time increases. However, the use of the replication factors may be inflating this as addressed below.
 
- >  The Swiss grid had an emission factor of ~150gCO2eq/kWh in 2022 (according to electricitymap). On the other side Azure in Switzerland has an emission factor of ~11gCO2eq/kWh (according to the cloud carbon footprint tool). There's a significant difference. What is the source of this ~11gCO2eq/kWh emission factor for Azure in Switzerland? Do you know how such a low emission factor, compared to the grid in the country, is achieved?
    - We obtain most of our emissions factors for Azure by locating data center locations published on Azure's site and cross-referencing location with [carbonfootprint.com's published data](https://www.carbonfootprint.com/docs/2022_03_emissions_factors_sources_for_2021_electricity_v11.pdf) based on 2020 emissions factor data. We focus on location-based emissions, and therefore reference the production mixed column of that data source. The discrepancy could be coming from the difference in data sources, the years, and with the biggest one being the method in which the electricity map calculates the carbon intensity -- which looks to be calculated [based on consumption](https://app.electricitymaps.com/faq) rather than production like on carbonfootprint.com's data).  Unfortunately, I don't know much about the tool and its sources to speak beyond those possibilities. 

- > For the compute estimator, is it correct to multiply the hours with the number of vcpus on line [59](https://github.com/abeggchr/cloud-vs-premise/blob/5c373abd659fefbd9f03acce27b347eb55958661/comparison.test.ts#L59). In the previous version, I only used the hours.
    - Yes, this is correct. We do the same within our approach for [Azure and AWS[(https://www.cloudcarbonfootprint.org/docs/methodology#networking)

- > memory and compute emissions are roughly in the same order of magnitude. Depending on the utilization, one of them is higher than the other. Is this comparable to other (real life) projects?
    - This is to be expected since they both are associated with cpu usage. While it depends on the configuration, memory is usually less as we calculate excess usage that isn't already included within the compute estimations You can read more about this in our [memory section](https://www.cloudcarbonfootprint.org/docs/methodology#applying-the-coefficient).

- > For the embodiedEmissions estimator, is it correct to multiply the embodiedEmissions of a single VM with the replicationFactor on line [128](https://github.com/abeggchr/cloud-vs-premise/blob/5c373abd659fefbd9f03acce27b347eb55958661/comparison.test.ts#L128). Why is the replication factor ignored by the EmbodiedEmissionsEstimator?
    - You shouldn't need to do this. This should only be set to the mapped Scope 3 emissions associated with that instance type for the CPU. You can see an example of how we get this for Azure in the [ConsumptionManagement file](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/ee4461439a88aff287966e92096c3d8a88fb7012/packages/azure/src/lib/ConsumptionManagement.ts#L1011).
  
- > For the embodiedEmissions estimator, on line [138](https://github.com/abeggchr/cloud-vs-premise/blob/5c373abd659fefbd9f03acce27b347eb55958661/comparison.test.ts#L138), to get the kWh based on CO2, the emission factor of the cloud data center is used. Is this correct from a methodological point of view? I am wondering, because the hardware is not produced with this emission factor but rather a way higher emission factor.
    - This is correct. Unfortunately, we don't have a way of annoying the actual location-based emissions factor from where the machine was manufactured. Therefore, we have to make the assumption that the most of the emissions associated with its lifecycle (i.e. decommissioning) will occur in the same region as the data center thus calculating associated kWh from that.
    
I hope this helps! As a heads up, you may be interested in checking out our [Lookup Table](https://www.cloudcarbonfootprint.org/docs/creating-a-lookup-table/) approach as you continue to experiment with custom machine specs. It will apply the CCF methodology for you by generating a co2e coefficient based on a single unit of usage for a machine/service from the input data you provide. It may be helpful to use this approach as it can save you time from manually building and implementing each estimator.

**Comment by abeggchr** [comment]
That's amazing, thanks a lot @4upz - this answers all questions I currently have!

**Comment by 4upz** [comment]
Awesome, happy to help! I hope your research goes well! Feel free to share any feedback or thoughts that may come from it.
