### ISSUE TITLE
Command-line tool ignores configuration file if region argument is included

### ISSUE THREAD

**Issue by jon-peterson** [cloud-carbon-footprint/cloud-carbon-footprint#1054]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Linux
- **Browser:**
  - None (CLI)

### Expected Behavior

Configure the CLI tool to use AWS cost and usage data from Athena (i.e., in `.env` file set `AWS_USE_BILLING_DATA` to true and do not specify any `AWS_ACCOUNTS`). Run the CLI tool over an arbitrary date range with the `region` set to any region.

The expected behavior is that the CLI tool will obey the settings in the `.env` file, and query Athena for the cost and usage report.

### Actual Behavior

The CLI uses the `AWS_ACCOUNTS` tags to fetch data instead. Because no `AWS_ACCOUNTS` are set up in the configuration file, no data is returned.

### To Reproduce

Run the command line above, specifying a region:

```
$ yarn start-cli --startDate 2023-02-01 --endDate 2023-02-09 --region us-east-2 --groupBy day
```

 To get the CLI to actually query the CUR in Athena, run the CLI without the `region` 

```
$ yarn start-cli --startDate 2023-02-01 --endDate 2023-02-09 --groupBy day
```

### Screenshots

None

### Additional Information

The problem is in the `App.js` file's `getCostAndEstimates` method, which has an if clause for `request.region` that improperly always tries to fetch from `AWS_ACCOUNTS`. Indeed, if you send in a region, you can't get data from GCP or Azure either.

© 2021 Thoughtworks, Inc.

**Comment by camcash17** [comment]
Hi @jon-peterson, thanks for submitting this issue!  Currently, if you are to set a `region` in the configuration, you will be taken down the path of the unsupported 'higher accuracy' [approach](https://www.cloudcarbonfootprint.org/docs/alternative-data-approaches#unsupported-using-cloud-usage-apis-higher-accuracy) which uses specific cloud API's. Otherwise, you will be able to use the billing data approach and gather AWS data from the Cost and Usage Reports. 

After review, it seems that this may not be very clear and you may have pointed out a bug in our code in `App.js` when running through the conditional logic. We will create a bug fix issue to address that and update the documentation to be more clear. In the meantime, just make sure you are not setting any region in your configuration unless you intend to use this approach.
