### ISSUE TITLE
API Deployment

### ISSUE THREAD

**Issue by sixc-ben** [cloud-carbon-footprint/cloud-carbon-footprint#1056]
### Preflight Checklist
- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - macOS 13.1
- **Browser: Chrome**
  - Chrome

### Expected Behavior

Non-errored start.

### Actual Behavior
```
cloud-carbon-footprint/packages/app/src/index.ts:5
export { default as App } from './App'
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/benbrooks/Downloads/cloud-carbon-footprint/packages/api/dist/api.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

### To Reproduce
```sh
$ git clone https://github.com/cloud-carbon-footprint/cloud-carbon-footprint.git 
$ cd cloud-carbon-footprint
$ yarn install
$ cd packages/api
$ yarn build
$ yarn start:webprod
```

### Additional Information

I'm interested in deploying the api & client to AWS/GCP and was attempting to locally test the instructions in the [Deploying](https://www.cloudcarbonfootprint.org/docs/deploying) section of the docs, particularly the `npm run start:webprod` command located in `packages/api/app-production.yaml`. Please let me know if I'm misunderstanding deployment steps!

© 2021 Thoughtworks, Inc.

**Comment by sixc-ben** [comment]
I addressed this problem by doing a Docker deployment instead. I have a feeling that I wasn't building/transpiling the web app correctly. It would be helpful if there was more documentation as to the various `build` commands in the `packages/api/package.json` and `packages/client/package.json` files.

**Comment by 4upz** [comment]
@sixc-ben Thanks for opening up this issue and for your update on resolving it!

Just for clarity and context, the steps that you were producing were correct. The issue was not from the build scripts, but instead the environment you were trying to replicate them in. The main repository's monorepo environment and local packages were what was getting in your way. The error you encountered was coming from the `App` package that the `API` relies on. This is due to your now-built API's CommonJS files trying import the local version of the `App` package which is still in Typescript. To resolve this issue, you would have to either build every other CCF package as well, or do some NPM magic to have your local `API` package rely on the published (and compiled) version of all CCF peer dependencies rather than the local packages in the monorepo.

The Google App Engine steps have the `API` and `Client` packages deployed separately, in which all CCF peer dependencies like the `App` package are installed as their published versions to go into the `node_modules` folder. This is the same reason the Docker deployment works, as the `API` and `Client` containers are the same isolated environment. 

To correctly replicate those steps locally, you would have to create a similar App environment using the [Create-App method](https://www.cloudcarbonfootprint.org/docs/create-app) and then run the same install, build, and start commands within that API folder. The Create-App method creates a CCF instance in which all of the non user-facing packages like the `App` packages remain as npm modules, allowing for easier setup and deployment for this case.

Hope that helps! We're happy to review our deployment documentation to see how we can make any local testing more clear as well. For now, I'll go ahead and close this issue, but feel free to leave another comment if you have more questions or issues.
