### ISSUE TITLE
Static map showing carbon intensity values

### ISSUE THREAD

**Issue by shreyansh-24** [cloud-carbon-footprint/cloud-carbon-footprint#1077]
- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - 
  - Windows 10
- **Browser:**
  - 
  - Chrome

### Expected Behavior

Map Data calculated from the provider data dynamically.

### Actual Behavior

Map showing Carbon Intensity values for various cloud provider regions is hardcoded and is an image.
Is there plan to make the carbon intensity to be calculated from time to time for each region and making it more dynamic ?How is the carbon intensity values calculated in your case ?Please explain.

Link: 
AWS : https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/client/src/pages/EmissionsMetricsPage/CarbonIntensityMap/AWSMap.png
AZURE : https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/client/src/pages/EmissionsMetricsPage/CarbonIntensityMap/AzureMap.png
GCP :  https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/client/src/pages/EmissionsMetricsPage/CarbonIntensityMap/GCPMap.png

**Comment by ericksod** [comment]
Hi @shreyansh-24 
This was an initial approach to displaying regional carbon intensity.
We have lightly explored making this interactive and dynamic but have not prioritized it due to not hearing a large ask around this feature from the community.
As for the carbon intensity values calculation, please see this explanation on the grid emissions factors we use: https://www.cloudcarbonfootprint.org/docs/methodology#appendix-v-grid-emissions-factors and information from cloud provider websites on data center location and additional carbon factor info when available (Google Cloud).
