### ISSUE TITLE
Want to have an public method to just calculate the AWS carbon emissions of existing billing data.

### ISSUE THREAD

**Issue by HankLeo** [cloud-carbon-footprint/cloud-carbon-footprint#1084]
Hi,

Very nice project and now I'm using your methodology in my project. But now I meet one problem.

I'd like to calculate the carbon emissions by using our existing AWS billing data, instead of providing the cloud account credential. 
I know that there's a lookup table way to get the result by send the input lookup data (https://www.cloudcarbonfootprint.org/docs/creating-a-lookup-table). But the method is not support to send the usage amount. It needs to multiply the result by myself. 
I attached as below, you can see the usage amount is hard coded as 1.
```
inputData.map((inputDataRow: LookupTableInput) => {
      const costAndUsageReportRow = new CostAndUsageReportsRow(
        null,
        '',
        '',
        inputDataRow.region,
        inputDataRow.serviceName,
        inputDataRow.usageType,
        inputDataRow.usageUnit,
        inputDataRow.vCpus != '' ? parseFloat(inputDataRow.vCpus) : null,
        1,    // hard code as 1 here
        1,
        {},
      )
```

Actually, my AWS billing data is very similar with the "CostAndUsageReportsRow" and I'd like to set up these usage data and build the report data by using my own data model. I realized that, the function "getFootprintEstimateFromUsageRow" in "https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/aws/src/lib/CostAndUsageReports.ts" is what I want exactly. But the method is declared as private as below.
```
private getFootprintEstimateFromUsageRow(
    costAndUsageReportRow: CostAndUsageReportsRow,
    unknownRows: CostAndUsageReportsRow[],
  )
```

Because I imported the @cloud-carbon-footprint/aws as a 3rd party library in my project, I will not change the source code of it. Can you help change this method to private so I can use it directly?😄

## Possible Implementation

Change the private function "getFootprintEstimateFromUsageRow" to public in "https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/aws/src/lib/CostAndUsageReports.ts"
```
**public** getFootprintEstimateFromUsageRow(
    costAndUsageReportRow: CostAndUsageReportsRow,
    unknownRows: CostAndUsageReportsRow[],
  ): FootprintEstimate | void
```

**Comment by HankLeo** [comment]
I also submitted a pull request as the detailed requirement what I prefer to have.

**Comment by 4upz** [comment]
Hi @HankLeo thanks for using CCF and we're glad you're enjoying the project! I appreciate the PR as well, it definitely helps by showing the proposed changes.

This seems to be an interesting situation as the Lookup Table actually does seem to be more of the better fit here. It hardcodes the value as 1 because it calculates the emission for 1 unit of usage, and expects you to multiply the result by your actual usage amount. I know that you may not want to do this manually, but have you considered doing this formulaically via calculations within the resulting spreadsheet or programmatically by parsing the resulting units? You should be able to use tools such as [csvtojson](https://www.npmjs.com/package/csvtojson) as a fairly straightforward way to implement this.

Since that is the recommended approach for custom data models, I want to be make sure the options for using it are exhausted before we begin changing the access to class methods for a specific use case -- especially since we would have to consider doing the same for the BillingExportTable (GCP) and the ConsumptionManagement (Azure) classes in order to keep the implementations consistent across providers.

**Comment by HankLeo** [comment]
Hi @4upz 
Sorry for the late response. 
It's OK to me if I need multiply the usage amount for unit carbon emission. But just think the CostAndUsageReportsRow is a more flexible model to me. So it's just a nice-to-have requirement to me~
So thanks for you reply!

**Comment by 4upz** [comment]
@HankLeo No worries! You do make a good point. We'll give some thought and come up with a plan on how to either make the usage of the Lookup Table more flexible to require less manual work or the cloud provider packages more modular/consumable.
