### ISSUE TITLE
Azure Recommendations not getting fetched

### ISSUE THREAD

**Issue by shreyansh-24** [cloud-carbon-footprint/cloud-carbon-footprint#1096]
- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Windows 10 (1803) 
- **Browser:**
  -  Chrome

### Expected Behavior

On providing my Azure portal Credentials, the CCF tool should be able to provide recommendations and details just like it does for my AWS account.

### Actual Behavior

Not able to get Recommendations for my Azure Account.

### To Reproduce

Provide all required Azure Credentials to CCF tool and access the Recommendation api i.e. /api/recommendations or Navigate to the recommendation tab on CCF Client. No data for Azure Recommendations

**Comment by 4upz** [comment]
Hi @shreyansh-24 thanks for using CCF and trying out the Azure recommendations! The Azure recommendations feature is early in its release since V1.0.0 of the Azure package, so we're still finalizing documentation and improvements for it -- so thanks for bearing with us and trying it out!

We see you could be facing this issue due to two possible issues:

1. The associated account has improper role/permissions assigned for fetching recommendations from the Azure Advisor Service
2. The associated account does not have any pending rightsizing/shutdown recommendations from the Azure Advisor Service

For the first possibility, this is least likely as you would typically see an error or log to the API console if there was an authentication error when querying the Advisor API. Just in case, we have the following roles assigned to our Azure account in order to get both recommendations and usage data:
```
Billing Reader
Cost Management Reader
Virtual Machines Reader
```

if you're sure that you have the proper permissions set from the first option, then the second option will be the most likely case as to why you're not seeing recommendations. Our implementation currently only supports rightsizing or shutdown recommendations for virtual machines. If your account does not have any VM resources nor any unoptimized VMs, then it's likely that there are no recommendations to show. You can confirm this by viewing the Advisors dashboard in your console and seeing if it shows any recommendations that match those types.

Hope that helps! Let me know if you're seeing any discrepancies with the second option. Happy to explore the issue further if you have recommendations in the console that are still not showing.

**Comment by 4upz** [comment]
Closing since there are no action items on our end. However, feel free to leave a reply to keep the discussion going. Happy to reopen or convert to a discussion post if needed.
