### ISSUE TITLE
Co2e Calculation based on Cost instead of Usage

### ISSUE THREAD

**Issue by shreyansh-24** [cloud-carbon-footprint/cloud-carbon-footprint#1097]
- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  -  Windows 10 (1803)
- **Browser:**
  - Chrome

### Expected Behavior

**Emission/footprint calculation should be based on Usage instead of Cost incurred**. The Carbon emission or footprint calculation that the CCF tool does is on the basis of Cost incurred on Using Cloud Services and the source is either Billing Reports in case of AWS and Invoicing in case of Azure. but in a Scenario where Customer is getting some good discounting on the cost then Actual usage would not reflect on the Cost and Usage Report or Invoice that is used by CCF to convert it into energy.

### Actual Behavior

The tool Takes Billing/Cost incurred information from different cloud providers, converts them into energy and hence the emission.

### To Reproduce

Connect the tool with an account having some discounting on total Cost and Usage report or invoice and check the footprint. It will show footprint in accordance with only the cost incurred but not the Usage.

**Comment by 4upz** [comment]
Hi @shreyansh-24, thanks for bringing this up. We've had some similar conversations around this, mainly pertaining to how our choice for using Blended Costs for AWS could impact the kWh/$ relationship due to potential discounts included. The theory is that this would leave to overestimation, rather than underestimation from missing usage. You can view that [conversation here](https://groups.google.com/g/cloud-carbon-footprint/c/7RE6OmA5rjU), and feel free to add any thoughts or insights. 

While the conversation focuses on emissions per dollar ratio, I don't believe we've come across an instance in which billing discounts have affected the usage amount reported. It's been my understanding that AWS' CostAndUsage as well as Azure's ConsumptionManagement both report usage as-is, with any discounts applied showing up as a separate line item relative to currency. This typically could also affect the total cost line item itself, which we do not use to determine emissions and energy estimates, and is only used to display cost alongside resulting estimates for a service. 

If you have an example of discounts directly causing usage amounts to be more or less than actual usage (i.e. vCpu hours reported, storage amount, etc), or perhaps even a comparison of differences across estimations for similar accounts, please feel free to provide them! Due to the wide variety of billing agreements, infrastructure setup, and account configurations that are possible across each provider, we rely on community feedback for full transparency into these type of cases. We'd be happy to dive deeper into this if this is an issue that users are seeing.

**Comment by 4upz** [comment]
Closing since there are no action items on our end. However, feel free to leave a reply to keep the discussion going. Happy to reopen or convert to a discussion post if needed.
