### ISSUE TITLE
Implement getCosts for Google Compute Engine

### ISSUE THREAD

**Issue by NFRBEZ** [cloud-carbon-footprint/cloud-carbon-footprint#1109]
GCP is getting wider usage over time, so it would be nice to get access to these data 

## Feature Suggestion
**Is your feature request related to a problem? Please describe.**
From now, using getCosts() on compute engine return a not implemented warning. It would be great to get data from these

**Comment by 4upz** [comment]
Hi @NFRBEZ , thanks for the suggestion! 

I assume you're referring to this function: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/c4c7e56407674a40b14347b75258a6dcdcc54765/packages/gcp/src/lib/ComputeEngine.ts#L122

If so, this seems to be a lingering function during early development of our app that remains in the codebase. It should probably be removed, as we don't have plans to implement this function due to cost data being already available with estimates when using the main Billing Data approach.

For additional context, the entire ComputeEngine class is only used as part of the now unsupported [Cloud Usage API approach](https://www.cloudcarbonfootprint.org/docs/alternative-data-approaches#unsupported-using-cloud-usage-apis-higher-accuracy) for GCP. With this approach, only GCP estimates for Compute Engine was possible. We don't plan on adding new features to this approach due to it giving a less holistic view of usage, limited support for services, and lack of consistent availability across cloud providers. 

Hope this helps! Feel free to let us know if you have additional questions or suggestions

**Comment by NFRBEZ** [comment]
Oh sure, alright

By then, to make it work on GCP, i should full all bigquery related field, and it should be fine, is that right?

**Comment by 4upz** [comment]
@NFRBEZ Yes, if you're grabbing estimates and have connected your billing account as described in the [GCP documentation ](https://www.cloudcarbonfootprint.org/docs/gcp) then you will have a cost field included with each estimate.
