### ISSUE TITLE
[Bug]: AWS estimation - Athena query errors when the account does not have any EC2 hours

### ISSUE THREAD

**Issue by ntmggr** [cloud-carbon-footprint/cloud-carbon-footprint#1170]
### Issue Details

Cloud Provider: AWS

### Expected Behavior

Athena query should run without problems

### Actual Behavior

```Athena query failed. Reason SYNTAX_ERROR: line 7:25: Column 'product_vcpu' cannot be resolved. Query ID: 3f4b5036-f041-4634-84a9-45a37125c595```

Stack Trace:
```"stack": "Error: Athena query failed. Reason SYNTAX_ERROR: line 7:25: Column 'product_vcpu' cannot be resolved. Query ID: 3f4b5036-f041-4634-84a9-45a37125c595\n    at CostAndUsageReports.getQueryResultSetRows ```

### To Reproduce

Run the estimation in an AWS account that has never run any EC2 instances

**Comment by 4upz** [comment]
Thanks for opening this issue @ntmggr! It seems this issue has come up before in #783., although there didn't seem to be a clean solution.

We're currently looking into this to see if it's consistent behavior with accounts not having any historical EC2 usage as you've described. You can verify this by using a `Describe <table_name` statement in the Athena console. It's possible that this may have been overlooked due to an account with this environment being less common. We'll leave an update here with our findings along with a potential fix for it.

In the meantime, if you don't mind tinkering a bit, you can modify the line in `CostAndUsageReports.ts` and removing the select statement that says `product_vcpu as vCpus`. A less favorable approach could also be to spin up and close down a free-tier EC2 instance so that the column is populated in your billing table.
