### ISSUE TITLE
[SPIKE] Adding Memory into our estimations

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#193]
#### Overview
One of our aims is to have as accurate a methodology and estimations as possible. To date, we estimate for storage, compute, and networking, but not memory. We would like to explore adding this in.
We can begin by reviewing the work done by Benjamin at Teads
## Acceptance Criteria
- [x] Review [https://medium.com/teads-engineering/evaluating-the-carbon-footprint-of-a-software-platform-hosted-in-the-cloud-e716e14e060c](https://medium.com/teads-engineering/evaluating-the-carbon-footprint-of-a-software-platform-hosted-in-the-cloud-e716e14e060c)
- [x] Review [https://github.com/teads/turbostress](https://github.com/teads/turbostress)
- [x] Review [https://medium.com/teads-engineering/estimating-aws-ec2-instances-power-consumption-c9745e347959](https://medium.com/teads-engineering/estimating-aws-ec2-instances-power-consumption-c9745e347959)
- [x] Further conversations with Benjamin?
- [ ] Document further research needed or unknowns
- [x] Determine what an approach could look like

## Tech Tasks
- [ ] Run Changesets, bump any packages that have been updated/changed

**Comment by ghost** [comment]
Based on our research, the first approach would be:

- We can establish an average threshold ( GB / vCPU ) for each instance type.
- For every instance that is over this threshold we can apply the extra consumption of 0.395 watt / GB

**Comment by github-benjamin-davy** [comment]
Hello, @roberto-thoughtworks I think that the average threshold should be based on the SPECpower dataset to be consistent with the methodology. Usually, the GB/vCPU scales linearly inside an instance type family (for example c5.12xlarge has 3 times more vCPU and GB of memory compared to a c5.4xlarge). The idea is that since the methodology uses computed average consumption per vCPU based on SPECpower datasets filtered on CPU microarchitecture, we would need to confirm that these datasets contain machines with a standard amount of memory (lower end) and that some cloud instances can have more than that. This would justify applying extra consumption. 
If we look at the average GB / CPU chip in the Skylake tab on the [CPU / Watts research](https://docs.google.com/spreadsheets/d/1O7Ug_eUZvbZA4dTaA-8DNhJhoZikKD2IdD8OeNQipe4/edit#gid=1258185692) document we can see that it is max 96 GB / CPU this would equal to an AWS c5 instance, in that case, it should be logical to apply the memory extra consumption for m5 and r5 instances that have the same type of CPU but onboard more memory (*2 & *3).

**Comment by ghost** [comment]
Hi @benjamindavyteads, thanks for the answer. You are right, we need to confirm that datasets contains machines with standard amount of memory. 
I believe that you can add more memory than default when creating an instance (at lest on AWS). In this case, if we detect that an instance has more memory than standard, we could add the extra consumption, right?

**Comment by github-benjamin-davy** [comment]
Thanks @roberto-thoughtworks I'm not aware of such a mechanism on AWS, it's possible to add storage but not memory/RAM, afaik the amount of memory is linked to the instance flavor you choose. 
Here you can consider the SPECpower machines as the standard and then compare with the amount of RAM available on the cloud instance. In my example for AWS, the m5 and r5 instance families have more memory than the SPECpower machines used to compute the consumption per vCPU so m5 and r5 instances should include the extra memory consumption.

**Comment by ghost** [comment]
@benjamindavyteads Yes, I was wrong about increasing the memory of AWS instances. 
Your approach make sense to me, thanks again!

**Comment by github-benjamin-davy** [comment]
Perfect, I've started to try it based on the original spreadsheet (AWS tab), you can have a look at it [here](https://docs.google.com/spreadsheets/d/1uh2Ua_ZlMNcchhrzykbvy-QXvmFHYttZnMFDq_hfqyw/edit?usp=sharing) I've simply calculated a per vCPU extra memory consumption for some instance types (needs to be completed).
