### ISSUE TITLE
Implement replication factors in the Storage estimation

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#232]
#### Overview
In our estimations for Storage, we have an opportunity to make it a bit more accurate. For storage when we have a certain amount of usage, there is a difference in that requested usage and the actual infrastructure being allocated (more is allocated for stability, reliability, backup, etc.)- this difference is the replication factor. We would like to take this into account in our calculations.
This card actually makes the change.

### GCP
- Replication factors are added to match this sheet: https://docs.google.com/spreadsheets/d/1JvSM2Z61hurpDl5uJvqrc5QoTyWYP6yLrQZ8tId3KOU/edit#gid=330120013

### AWS
-  Replication factors are added to match this sheet: https://docs.google.com/spreadsheets/d/1JvSM2Z61hurpDl5uJvqrc5QoTyWYP6yLrQZ8tId3KOU/edit#gid=735227650

### Azure
-  Replication factors are added to match this sheet: https://docs.google.com/spreadsheets/d/1JvSM2Z61hurpDl5uJvqrc5QoTyWYP6yLrQZ8tId3KOU/edit#gid=2008238628

## Tech Tasks
- [ ] Run Changesets, bump any packages that have been updated/changed

## Review Tasks
- [x] Update methodology to indicate the use of replication factors for storage. Link to public spreadsheet and include implementation status column

**Comment by dtoakley** [comment]
I've reviewed this and updated the implementation to what I think should be correct for Google Cloud. Notes:
- I added a new tab for all the GCP test cases in the spreadsheet, so we can better verify their correctness:https://docs.google.com/spreadsheets/d/1JvSM2Z61hurpDl5uJvqrc5QoTyWYP6yLrQZ8tId3KOU/edit#gid=386517795
- Some of the implementations weren't quite right - you can see the updates inside the `getReplicationFactor` function. 
- When there isn't a region returned from the BigQuery API and it's a Dual-Region or Multi-Region replication, we can use the `location.location` field to more accurately estimate the CO2e. I've added these options to `packages/gcp/src/lib/GCPRegions.ts` and their emissions factors in the new spreadsheet tab, and `GcpFootprintEstimationConstants.ts`. I also updated the BigQuery query to fall back to this if `location.region` is null. This *could* impact other types of Google estimates, but only in ways that would improve accuracy, by using a Dual/Multi Region emissions factor, rather than the global average used for `unknown`. 
- Arguably the `Cloud Memorystore` usage rows should be classified as memory, not storage. But given the `usage_type` is `byte-seconds` it could well be storage under the hood, as this is the only example of a potential memory usage not being in `bytes`. Also it would require some additional refactoring, including converting byte-seconds to Gigabytes, which isn't all that trivial because the conversion would be affected by whatever `GROUP_QUERY_RESULTS_BY` is selected in the Config. So I think it's fine for now.

**Comment by dtoakley** [comment]
Updates from me:
- Reviewed AWS and updated the implementation -- I think it's in a good spot now. See the AWS tab in the spreadsheet for details on the tests I added and changed. Some call outs: only the `TimedStorage` and `EarlyDelete` S3 usage types should get replication factors; Aurora Storage is SSD; `BackupUsage` for the managed services like DocDB and RDS are stored in S3, so they get the same replication factor. 
- Updated the GCP implementation to support replication factors for Compute Engine Snapshots and Image Storage, because they are stored in Cloud Storage and should get those same replication factors, based on whether it's Multi or Dual-Regional. 
- Refactored the GCP Replication Factor logic into it's only file. Benefits: it better adheres to Single Responsibility; we avoid the switch statement using object literals instead; it's more extensible if we want to use this logic outside the BillingExportTable class in the future. 
- Before starting on Azure, I recommend doing a similar refactor for the AWS Replication Factors.

**Comment by dtoakley** [comment]
This is looking good now for all cloud providers. I've updated the draft methodology with a new section for "Storage Replication Factors" (https://docs.google.com/document/d/1kchqv4GVd5nvdVuhU47eTcoSeXk-twl3KNLAz4Rxvus/edit#) and linked a new copy of the spreadsheet that we will make public when we are ready (https://docs.google.com/spreadsheets/d/1D7mIGKkdO1djPoMVmlXRmzA7_4tTiGZLYdVbfe85xQM/edit#gid=735227650)

@ericksod please review, then we can update the microsite!
