### ISSUE TITLE
Boolean configuration options interpret `false` as `true`

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#244]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](../../CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - 
- **Browser:**
  - 

### Expected Behavior

- [x] When I specify false or empty string for client config options, it is interpreted as false
- [x] When I specify false or empty string for API config options, it is interpreted as false
- [x] When I specify false or empty string for CLI config options, it is interpreted as false

### Actual Behavior

Setting variables to false in .env files treats it as true

### To Reproduce

Set client/.env REACT_APP_PREVIOUS_YEAR_OF_USAGE=false, then load the application. It will make a request for the previous year of usage. 

### Additional Information

© 2021 ThoughtWorks, Inc.

**Comment by ghost** [comment]
The issue here is that env variables are strings, so we cant distinguish in true or false. They are setted or not. Values true and false are the same (variable is setted in both cases). Also, it's confusing for users because if they see a variable with 'true' the logic is put 'false' to disable that option.
- One solution is specify in docs that the way of disable a variable is leaving it empty
- The other solution is change the config files and check if `process.env.variable === 'true'`. This way if it has 'false', it will be false.
