### ISSUE TITLE
Update coefficients from SPECPower Database

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#253]
#### Overview
We would like to keep our application up to date with the most recent data. This includes those from the SPECPower Database.
## Acceptance Criteria
- [ ] When I estimate the emissions for my usage, the core package uses the most up to date SPECPower Database numbers on energy consumption.

## Tech Tasks
- [ ] Run Changesets, bump any packages that have been updated/changed

## Review Tasks
- [ ] Update methodology to reflect updates

**Comment by davidmytton** [comment]
I'm looking at whether I can help update the coefficients for this issue but could do with some pointers on where the current values are sourced from:

1. Are you taking values from https://www.spec.org/power_ssj2008/results/power_ssj2008.html as described in https://www.cloudcarbonfootprint.org/docs/methodology#energy-estimate-watt-hours ?
2. Is there a reference for the source of each value? For example which SPECpower database entry is the value of `0.62` for the GCP `COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE` taken from in https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/84ce75ea0efbd259bfe736b2a512424bec5cb2e7/packages/core/src/domain/FootprintEstimationConstants.ts#L45
3. Are the median and mean values being calculated manually based on the input values e.g. for the value of https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/84ce75ea0efbd259bfe736b2a512424bec5cb2e7/packages/core/src/domain/FootprintEstimationConstants.ts#L43
4. I assume these are pulled manually at the moment but has any thought been given to automatic updates from the quarterly SPECpower updates? 
5. Are you making a utilization adjustment to the SPECpower value or does this happen elsewhere? I assume elsewhere because SPECpower provide them for 100% utilization and idle, which I assume translates to the `MAX` and `MIN` coefficient constants?
6. Are there any other sources being used for the CPU values?

I'm assuming this requires updating the values in https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/84ce75ea0efbd259bfe736b2a512424bec5cb2e7/packages/core/src/domain/FootprintEstimationConstants.ts

Thanks!

**Comment by dtoakley** [comment]
Hey @davidmytton -- thanks so much for looking into this! I'll try my best to answer your questions:

1. Yes, that is the data set that we are using as the starting point for determining the Compute coefficients. 
2. The ways that it works is as following:

-  We pull in the SPEC Power dataset in this spreadsheet: https://docs.google.com/spreadsheets/d/1O7Ug_eUZvbZA4dTaA-8DNhJhoZikKD2IdD8OeNQipe4/edit#gid=467435557 in the "SPEC Power Full Results (Jan 2021)" tab. (This tab will need to be renamed once the coefficients are updated). This spreadsheet is linked to from Appendix II in the methodology, and you can see we currently have 735 rows, whereas the current SPEC Power dataset has 754, so we are missing 19 rows that have been added since January 2021. So the first step would be to pull in the missing 19 rows. 
- For Intel based processors, we determine which microarchitecture they are. If you scroll down in the same tab, you can see we do this with a TRUE/FALSE formula using the "List of Intel Processors" tab. 
- Based on that, we can then copy those 19 rows over into the corresponding Tab for that microarchitecture (Skylake, Cascade Lake, or AMD EPYC 1st/2nd Gen, etc).
- In each of those microarchitecture Tabs, columns Q & R show the min and max watts at o% and 100% utilization, and if you scroll down to the bottom of them, we determine the average for each microarchitecture. For example, in the Coffee Lake Tab, we look at Q13 and R13. Based on adding the additional 19 rows, some of these coefficients will change slightly, which will then need to be updated in  the `cloud-carbon-footprint/packages/core/src/domain/FootprintEstimationConstants.ts` file. 
- Because this spreadsheet is public and readonly, I suggest maybe making a copy of it with the changes that we can cross reference, then merge the updates into the main public readonly version. 

3. For the median and mean values, you can look in the same spreadsheet at the "AWS - Compute", "GCP - Compute" and "Azure - Compute" tabs at the beginning. For example, cell E8 in "AWS - Compute" shows how the get the average for AWS. The other two providers should be easier to find. These formulas shouldn't change, but once the coefficients update, the result will be slightly different. 

4. Yes, manual at the moment :) But we would be very open to suggestions of how to better automate the process, whether that is via code or a low/no code approach like Zapier. 

5. I think my answer to qsn 2 might cover this, but no we are not adjusting the utilization from the SPEC Power database. 

6. No. I think what I've outlined here should be all the data sources you need.

**Comment by davidmytton** [comment]
Thanks for explaining - I didn't see that Google Sheet! I'll have a look through and see if I can submit a PR for this over the next few days.

**Comment by davidmytton** [comment]
I've just opened https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/314 as a draft with the updated coefficients, but would like to request some help before it can be merged:

I made [a copy of the Google Sheet](https://docs.google.com/spreadsheets/d/1TSoINc8mkEOSlBi64wCLNp1iWxBgU6w9-n2bD8miqmw/edit?usp=sharing) and have included the updated equipment tests. Of these, there is just a single new Intel chip - "Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz" on row 738 of tab "SPEC Power Full Results (Q2 2021)". This is a Cascade Lake chip. I have added this to the "Cascade Lake" tab line 73 which updates the averages.

1. There are several new AMD EPYC chips but these are all Gen 3, which is not represented on the sheet on the coefficients. Are we leaving those out for now?
2. Azure and AWS tests failed so I updated those test files as part of 39b51f5fbbc70a647bd214af17a19c12ea2a78cb but is there a way to validate the calculations other than what is reported as part of the test run?
3. `src/__tests__/cli.test.ts` is now failing and I have not fixed this pending an answer above, in case you have a way to validate the numbers rather than blindly updating the tests. For example this failing test has a result for `ComputeEngine` which goes from `0.00` to `5.78`, which seems like a large change but is one I'm unsure how to validate:

```cli › ebs, s3, ec3, elasticache, rds › ebs, s3, ec2, elasticache, rds grouped by service

    expect(received).toMatchSnapshot()

    Snapshot name: `cli ebs, s3, ec3, elasticache, rds ebs, s3, ec2, elasticache, rds grouped by service 1`

    - Snapshot  - 2
    + Received  + 2

    @@ -2,7 +2,7 @@
      | EBS          | 6.08              | 0.002602               | $9.23             
      | S3           | 0.08              | 0.000036               | $12.00            
      | EC2          | 39.48             | 0.016895               | $74.00            
      | ElastiCache  | 24.06             | 0.010295               | $12.00            
      | RDS          | 464.46            | 0.198774               | $18.47            
    - | ComputeEngine| 0.00              | 0.000000               | $0.00             
    + | ComputeEngine| 5.78              | 0.002892               | $0.00             
    - | Total        | 534.15            | 0.228601               | $125.70           
    + | Total        | 539.94            | 0.231494               | $125.70

      172 |       const result = await cli([...rawRequest, '--groupBy', 'service'])
      173 |
    > 174 |       expect(result).toMatchSnapshot()
          |                      ^
      175 |     })
      176 |
      177 |     test('ebs, s3, ec2, elasticache, rds, grouped by day', async () => {

      at src/__tests__/cli.test.ts:174:22
      at step (src/__tests__/cli.test.ts:63:23)
      at Object.next (src/__tests__/cli.test.ts:44:53)
      at fulfilled (src/__tests__/cli.test.ts:35:58)
```
4. You mentioned the median/mean calculations but I'm not clear on where those are from. In your example, cell E8 in 'AWS - Compute' is labelled as Max Watts for Graviton A1 but the formula is the average of the Max Watts across all CPU types. This matches with https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/86a253612d400c67291e43f3301946f7ea35f1d4/packages/core/src/domain/FootprintEstimationConstants.ts#L146 so I assume the spreadsheet is just somewhat misnamed. However, for GCP median at https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/86a253612d400c67291e43f3301946f7ea35f1d4/packages/core/src/domain/FootprintEstimationConstants.ts#L43 is this value in cell C12 or C13 from the "GCP - Compute" tab?
5. For memory, the values in the "AWS - Memory" cells N2:P12 seem to be hard coded. I assume these need updating to do the calculation?

**Comment by dtoakley** [comment]
Thanks again @davidmytton -- this is looking good so far. Before I answer your questions -- we have recently separated the cloud providers into their own packages, which includes the Compute/Memory coefficients. (This duplicates the values in 3 places, but we want to make it easy for consumers of the app to update them per cloud provider if they want to use different values.) Unfortunately, this change has caused your branch to have some conflicts, and I think it might be easier for you to pull the latest on trunk and create a new branch with the changes (now in the 3x places), than to handle the conflicts (given the changes are small).  If you're able to do that, I think it'll help us verify things like the tests after you re-push.  

Now to your questions:

1. It looks like Azure recently released some instances using the AMD EPYC 3rd generation processors. Specifically the HBv3-series, of which there looks to be only one instance type currently: HB120rs v3. Source: https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/ So I think we might want to create a new tab for this generation in the spreadsheet and update the processors options with it, then add this instance type to `packages/azure/src/lib/VirtualMachineTypes.ts`. Although, that change is a little more complex, so we can separate it out to a different issue if you would prefer, and just focus this one on the Cascade Lake coefficient update.  AWS and GCP don't seem to be using this generation (yet). 
2. When we initially built out those tests, we manually determined the values in a spreadsheet before writing the tests using TDD. In this case however, I'm okay looking at your PR changes to be confident enough with the updated values, rather than re-doing that process and updating the tests first. 
3. Hmmm -- I think I'll like to pull your new branch and check this locally before I have a good response/recommendation :) 
4. This one is a little tricky, and sorry the spreadsheet isn't clearer. I've made comments in your copy to help resolve this, but I think what you have said is pretty much it. 
5. Correct - these shouldn't be hardcoded but instead pull from the relevant sheets, so Cascade Lake should be updated in those cells. 

One last thought -- this is the kind of important but somewhat complex change that would be good to pair on / discuss. If you want, I'd be happy to jump on a call and talk/walk through the spreadsheet with you. Feel free to email us at green-cloud@thoughtworks.com, or I'm happy to email you to connect as well :)

**Comment by davidmytton** [comment]
Thanks for the discussion @dtoakley-tw - the PR is now ready for review: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/314

**Comment by dtoakley** [comment]
Thanks so much @davidmytton ! For some reason your branch is showing many more commits than the changes needed for this issue. I pulled your changes and re-pushed a ner branch to origin with your changes, which you can see here: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/333

Everything looks good, and I've updated the public spreadsheet with the new coefficients: https://docs.google.com/spreadsheets/d/1O7Ug_eUZvbZA4dTaA-8DNhJhoZikKD2IdD8OeNQipe4/edit

I've merged it in, and created a new issue for the AMD EPYC 3rd Gen addition: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/332

Closing this one off.
