### ISSUE TITLE
Improve Azure documentation

### ISSUE THREAD

**Issue by vhiairrassary** [cloud-carbon-footprint/cloud-carbon-footprint#310]
We are trying to setup CCF for our Azure account. After having complete the [documentation](https://www.cloudcarbonfootprint.org/docs/azure/) we didn't get any result:
```
| Service      | kilowatt hours    | metric tons CO2e Emissions| Cost
| Total        | 0.00              | 0.000000               | $0.00
```

After debugging a bit, it seems no subscriptions are attached to newly registered Azure application. You have to follow the following process to do it: https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#assign-a-role-to-the-application

What do you think about:
- Improving the documentation by mentioning this;
- Log a warning or return an error when no subscriptions are returned here (I vote for an error, as when the credentials are wrong):
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/84ce75ea0efbd259bfe736b2a512424bec5cb2e7/packages/app/src/AzureAccount.ts#L47

I am willing to implement this changes if ok for you.

**Comment by ericksod** [comment]
@vhiairrassary Sorry for the delay but thanks for noticing this! We think both are great suggestions and would complement each other. If you're willing to implement one or both - adding in documentation to the Azure Connect with Real Data instructions and logging a warning that would be amazing. We think a warning rather than an error makes the most sense, since the issue isn't directly with cloud carbon footprint but rather an outside configuration that should be done.
If you are able to pick this up feel free to assign yourself to the issue and move it into the Doing column!

**Comment by vhiairrassary** [comment]
@ericksod Thanks for your answer, here is a PR https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/330 changing the documentation and emitting a warning when no subscription are returned.

Regarding issue assignment & project state, I don't have enough permission to do it.
