### ISSUE TITLE
Same env. var. for different options

### ISSUE THREAD

**Issue by vhiairrassary** [cloud-carbon-footprint/cloud-carbon-footprint#324]
Two options use the same env. var., is that expected?

https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/12170c4c2b763eb2cffe501fe938c5d8b2819e3d/packages/common/src/Config.ts#L94-L95

Actually it seems `targetRoleName` config. options is never used in the project: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/search?q=targetRoleName.

I would expect it to be used here:
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/12170c4c2b763eb2cffe501fe938c5d8b2819e3d/packages/aws/src/application/AWSCredentialsProvider.ts#L19-L31

Also, `packages/core/src/application/AWSCredentialsProvider.ts:` link at https://www.cloudcarbonfootprint.org/docs/aws/#options-for-aws-authentication is now a dead link.

**Comment by ericksod** [comment]
Hey @vhiairrassary! Thanks for the call outs.
Good catch on the dead links, we're handling it in https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/327
As for the possible duplicate env vars, we're going to refresh on what all of them are and how they're used, and look into that seemingly unused one in particular. Thanks! We'll leave this issue open until we determine next steps

**Comment by dtoakley** [comment]
I think we should remove the config option `targetRoleSessionName` and use `targetRoleName` in all the places it is being used, to remove the duplicate variable. This is because it makes more sense to use the role name as a session name, than using a session name for the role name  - hope that makes sense :)  This is a larger change, but logically make more sense than keeping the `targetRoleSessionName` option.

We could introduce a new env variable like `AWS_TARGET_ACCOUNT_SESSION_NAME` but I think that will unnecessarily increase the barrier to entry, and potentially cause more confusion.

**Comment by dtoakley** [comment]
I have implemented and pushed this change: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/7287f8bb6a8d6183f3d43e88cf0b557f8564f41b

Thanks again for the issue @vhiairrassary !

**Comment by vhiairrassary** [comment]
Thanks you for this 🙏
