### ISSUE TITLE
Include project id for GCP in data output

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#338]
#### Overview
In order to better analyze the data and understand the most valuable ways to look at it, many users, including our TechOps stakeholder and the ThoughtWorks data team are looking at the raw data itself. They would like to combine the data provided by our tool with other data, but for GCP without the project id, the only unique identifier, they cannot. This ticket will address adding in the project id to the set of data returned from the various ways of receiving CCF data.
#### Out of Scope:
- [ ] No changes should appear on the UI
## Acceptance Criteria
- [x] When I hit the API, and request GCP data, I should receive both the project name and the project id
- [x] When I hit the API, and request AWS data, I should receive both the account name and no value for the account id (or should this be switched or duplicated?)
- [x] When I hit the API, and request Azure data, I should receive both the subscription id and subscription name
- [x] When I request GCP data via the CLI, I should receive both the project name and the project id
- [x] When I request AWS data via the CLI, I should receive both the account id and no value for the project id (or should this be switched or duplicated?)
- [x] When I request AWS data via the CLI, I should receive both the subscription id and subscription name

- [x] _(Probably not possible - spend very short time testing)_ When I download data from the emissions breakdown chart, I can see both project id and name for all cloud providers if provided

## Tech Tasks
- [x] Run Changesets, bump any packages that have been updated/changed
- [x] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.
- [x] Test for performance implications - if so, let's talk about it

## Review Tasks
- [ ] eg. specific QA details, update methodology, or update microsite

**Comment by dtoakley** [comment]
For this, I think we can introduce a new attribute to the `ServiceData` type inside `packages/common/src/EstimationResult.ts`, for `AccountId`. How is how it will be handled for each cloud provider: 

- GCP: accountId: populated with project ID, accountName: populated with project Name
- AWS: accountId: populated with accountId, accountName: populated with accountId
- Azure: accountId: populated with subscription ID, accountName: populated with subscription Name

**Comment by dtoakley** [comment]
I've implemented this as specified in the previous comment. A few notes:
- The account name and id aren't exposed in the results via the CLI, in any of the options for how to render the tables. So those checklist items didn't need to be implemented. It should be a different issue to expose these, but only if we want to add that feature. 
- When downloading the data from the emissions breakdown chart, the project ID is not included in the results, after testing this. 
- There shouldn't be any noticeable performance implications from this, because GCP is the only cloud provider that now returns an additional object attribute when getting data from BigQuery, and GCP is already highly performant compared to AWS and Azure. AWS and Azure already returns the data we need from their APIs to populate the accountId field. 

Moving to review!
