### ISSUE TITLE
Question: How to map AWS account numbers to meaningful names?

### ISSUE THREAD

**Issue by jgrumboe** [cloud-carbon-footprint/cloud-carbon-footprint#459]
Fetching billing data from AWS Athena will always show me account numbers only in the dashboard.
How could I map those numbers to meaningful account names to display?

**Comment by ccasher** [comment]
Hi Johannes, thanks for bringing up this issue. Currently, the AWS Cost and Usage Report does not provide a column for Account Name, so there is no way to query it through Athena. I might suggest to see about adding Account Name to the CUR and updating the query we have written [here]() to include Account Name once it is added to the report.

Another suggestion would be to make your own custom map for Account ID's to Account Names in the code base and have the names be returned on the dashboard rather than the ID's. 

There might also be an AWS API to query and receive meta data that contains the account names per Account ID, and have those returned and mapped accordingly.

Would you feel comfortable looking into any of these options?

**Comment by jgrumboe** [comment]
Hi @ccasher 
I don't think that CUR supports an account name column.

Your second and third option are probably worth investigating. 

Ad 2) To have some hard-coded values in .env file would be the simplest solution. Maybe we could use the existing AWS_ACCOUNTS variable, which already exists for cost explorer queries.
It could be cumbersome for people with a lot of accounts to maintain it.

Ad 3) At least for AWS organizations there's an API I know https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListAccounts.html.
This would fit my usecase perfectly since I've configured our Billing/Organizations account for fetching data.
I don't know if this is working for personal accounts also.
At least this would be a nice solution with nothing to do (hardcode) for the user of CCF.

I could try the AWS_ACCOUNT solution as a quick win first.

**Comment by ccasher** [comment]
Okay, great! We just moved this to the Ready To Do column in our project board. Feel free to submit a PR if you come up with a solid solution.
