### ISSUE TITLE
Can not build projects with strictNullChecks:true when consuming @cloud-carbon-footprint packages

### ISSUE THREAD

**Issue by MichaelHindley** [cloud-carbon-footprint/cloud-carbon-footprint#476]
Given you have a project with "strictNullChecks:true" in tsconfig.json,
and you consume a @cloud-carbon-footpring package,
when you try to build using `tsc`,
you get 197 type errors from the different packages.

See [gist](https://gist.github.com/MichaelHindley/4715a1a0f2058c147bf47f0bccafbd17)
See [other this runtime issue due to ignoring null and undefined values](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/475)

**Comment by 4upz-tw** [comment]
Hi @MichaelHindley, just a quick update that we created a new issue (https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/568) to address this in greater detail since this seems to be an issue with multiple packages. As a result, we're going to close this one. Thanks again for pointing this out! In the meantime, we're currently looking into fixing the specific error that you encountered with the EstimationResults crash and have added it to our board.
