### ISSUE TITLE
Filters should apply to "Current Total" on Recs Dashboard

### ISSUE THREAD

**Issue by dtoakley** [cloud-carbon-footprint/cloud-carbon-footprint#493]
**Context:**
We have filters at the page level for the recommendations dashboard.
We would like these filters to help the user see particular content related to the specific drilldown they choose.

**A/C's**
- [ ] When I select a cloud provider in the cloud provider dropdown, I see a total CO2e that only takes into account that cloud provider
- [ ] When I select an account in the accounts dropdown, I see a total CO2e that only takes into account the selected account(s)
- [ ] When I select a region in the regions dropdown, I see a total CO2e that only takes into account the selected region(s)
- [ ] When I select a recommendation type in the recommendation types dropdown, I see a total CO2e that only takes into account the selected recommendation type(s)
- [ ] When I select a cloud provider in the cloud provider dropdown, I see a total cost that only takes into account that cloud provider
- [ ] When I select an account in the accounts dropdown, I see a total cost that only takes into account the selected account(s)
- [ ] When I select a region in the regions dropdown, I see a total cost that only takes into account the selected region(s)
- [ ] When I select a recommendation type in the recommendation types dropdown, I see a total cost that only takes into account the selected recommendation type(s)
- [ ] When I make selections or lack of selections that result in no data, I see 0 in carbon and cost

**Comment by ghost** [comment]
While testing, I noticed that the previous 30 days panel seems to correspond to the month to date (October 1st to 21st), not 30 days. This will need to subtract 30 days from the current date to be accurate.

**Comment by ghost** [comment]
Pulled down the data being sent to the staging and local environments, and the numbers aren't matching up. I'm fairly certain the culprit is the group by clause we're sending to the cloud providers. Daily grouping doesn't cause a mismatch, while monthly does.

We should verify the order in which grouping and date filtering logic is used in the query we send to the providers. For example, if we group by a month first then filter second, we would lose the ability to exclude part of a month (which we need if we're doing a 30 day window).

**Comment by ghost** [comment]
I believe https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/575 may be skewing the results. My thought is that if we can get that fixed, this might also be fixed. If not, that eliminates one possible cause so we can focus on the others.
