### ISSUE TITLE
For non zero numbers, show more info

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#495]
Currently on the Rec Table, there are still some values displaying 0 for carbon savings even with toggled to kilograms. We want to have these display "< 0.001".

*AC's*
- [ ] When toggling the rec table to display kilograms, there are no 0 values, only < 0.001.

**Comment by jeff-zinger** [comment]
Hi there, I'd like to pick this up. I should have time next week to do it.

**Comment by jeff-zinger** [comment]
After looking into the issue, I think the solution could be a little different to what has been described, so I've uploaded some screenshots of my implementation.

The mock "co2esavings" values - in `packages/client/stub-server/mockData.json` used to generate the screenshots are the following:

`0.01, 0.001, 0.0001, 0.00001, 0.000001, 0.0000001`

With their values after rounding 

`0.01, 0.001, '< 0.001', '< 0.001', '< 0.001', '< 0.001'`

and in kilograms

`10, 1, 0.1, 0.01, 0.001, '< 0.001',`

Please let me know if that's ok!

<img width="1543" alt="Screenshot 2021-10-28 at 14 18 18" src="https://user-images.githubusercontent.com/77101422/139253993-403799e2-084b-4382-a6bd-efa4188785f6.png">

<img width="1545" alt="Screenshot 2021-10-28 at 14 19 40" src="https://user-images.githubusercontent.com/77101422/139253985-0567572b-a8de-4675-aa17-bcde31525809.png">

**Comment by jeff-zinger** [comment]
I also noticed that the search doesn't work if the units are in kilogram. In the example below, inputting `2.8` finds the results, but if you change the units to kilograms `28` should find the same results, but instead it doesn't find them. 

However if your search for `2.8` and the units are in kilograms, it does indeed find the results as it is not checking that the units have been converted.

I can fix this quickly as well since i'm there!

<img width="1523" alt="Screenshot 2021-10-28 at 14 29 02" src="https://user-images.githubusercontent.com/77101422/139256852-2664b58e-452b-4105-8d77-cfec02d18ce0.png">

<img width="1523" alt="Screenshot 2021-10-28 at 14 29 27" src="https://user-images.githubusercontent.com/77101422/139256846-fdc602d9-b333-451e-ae04-0579868b7464.png">

<img width="1518" alt="Screenshot 2021-10-28 at 14 33 08" src="https://user-images.githubusercontent.com/77101422/139256838-a13fbf91-86db-4e4e-8365-13d54930e650.png">

**Comment by ericksod** [comment]
Hi Jeff! Thanks for that, we'll take a look. As for that implementation, it seems good to me. 
And also, excellent catch on that search with the kg - thanks!

**Comment by ericksod** [comment]
Hey @jeff-zinger 
Just wondering if you were still open to making the update to fix search for kg.
If so, let us know - if not, I'll make a new card for that bug.
Thanks!
