### ISSUE TITLE
Add config to disable file system logging

### ISSUE THREAD

**Issue by MichaelHindley** [cloud-carbon-footprint/cloud-carbon-footprint#504]
The current Logger logs to disk with no option to disable it. This makes it unable to run in serverless environments like AWS lambda, which do not provide a filesystem out of the box, but transport logs by network mechanisms.

**Comment by ericksod** [comment]
Hi @MichaelHindley! Sorry for the delay on this one - this is a good call out, we'll add it to the backlog.

**Comment by blueleader07** [comment]
@MichaelHindley I ran into this tonight ... I was attempting to run as a lambda and could not mkdir 'logs' because of the lambda read-only file system.  I am using the lookup table feature.

Here's a trick that worked for me.  It's not the best solution (sinon is meant for unit testing afterall) ... but if you need something now it might help.

```
import { Logger, LookupTableInput } from '@cloud-carbon-footprint/common'
import sinon from 'sinon'

const getAwsEstimates = async (awsInput: LookupTableInput[]) => {
    sinon.stub(Logger.prototype, 'error').returns()
    sinon.stub(Logger.prototype, 'warn').returns()
    sinon.stub(Logger.prototype, 'info').returns()
    sinon.stub(Logger.prototype, 'debug').returns()
    // now call cloud-carbon-footprint classes
    return new App().getAwsEstimatesFromInputData(awsInput)
}
```

**Comment by ericksod** [comment]
Hi all, 
We've discussed and came up with a possible solution:
If you change the LOGGING_MODE to GCP, then that will log into the console and not a file.
Hope this helps!
