### ISSUE TITLE
Forecast totals should have monthly time frame

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#515]
**Context**
As a user looking to make optimizations
I want to see the forecast in terms of months 
So that it is more relevant to current timeframe and provided recommendations

**Assumptions**
- [x] Forecast component should respond to the filters

**A/C's**
- [x] When I view the forecast component, I see the first box labeled "Last 30 Day Total" and the carbon and cost totals for the past month (30 days)
- [x] When I view the forecast component, I see the second box labeled "Projected 30 Day Total" and I see the carbon and cost totals for the past 30 days minus the monthly savings available as per recommendations shown in the table
- [x] When I view the forecast component, I see the third box labeled "Monthly savings equal to" and the equivalent tree seedlings planted for a month's worth of savings and the subtext "Tree seedlings grown"
- [x] When I view the third box of the forecast component, I see a month's worth of savings in dollars and the subtext "Dollars per month"

**Comment by ghost** [comment]
Added up the cost and carbon savings with a few filters set up and verified:

- "Monthly Savings Equal To" matched up with 1 seedlings grown (0.073 * 16.5337915448 = ~1.2) and a raw sum of 5347.488 dollars (though we may want to consider rounding up since the site said "5,347.48").
- "Projected 30 Day Total" correctly subtracted the cost of "$5,347.48" from "$329,138.87" to get "$323,791.39". Metric Tons C02e was roughly correct, with 7.74 - 0.073 producing 7.65 (raw calculation was 7.667, but that could be due to rounding somewhere).

The first acceptance criteria isn't technically met, but that could be more due to https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/493#issuecomment-948924311

**Comment by ericksod** [comment]
Posting the other comment here as well because it is more relevant to this card @TedGardner :
While testing, I noticed that the previous 30 days panel seems to correspond to the month to date (October 1st to 21st), not 30 days. This will need to subtract 30 days from the current date to be accurate.

**Comment by ghost** [comment]
Running locally, I wasn't able to reproduce the bug I saw on Thursday. I did notice that changing the "GROUP_QUERY_RESULTS_BY" environment variable away from month to either unset or year produced data that did match up between the home page and recommendations page, whereas grouping by month they did not match up.
