### ISSUE TITLE
[SPIKE] Embodied emissions

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#524]

**Comment by dtoakley** [comment]
After looking into this a bit, I think we can leverage the work done by Benjamin Davy @ Teads, as well as the SCI Standard to come up with Embodied emissions estimates for instances in the cloud. [This](https://medium.com/teads-engineering/building-an-aws-ec2-carbon-emissions-dataset-3f0fd76c98ac) is the relevant article, and [this](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#embodied-emissions--m) is the section in the SCI standard. 

I think we can first implement this for compute instances across all three major cloud providers, make sure we are happy with it, then consider how we can apply it to non-compute resources used, such as managed services, networking, etc. Here is the SCI standard variables and how we could use them within CCF:

- TE = Total Embodied Emissions, the sum of LCA emissions for all hardware components - I think we can leverage Teads' research and data set [here](https://docs.google.com/spreadsheets/d/1DqYgQnEDLQVQm5acMAhLgHLD8xXCG9BIrk-_Nv6jF3k/edit#gid=504755275) for this, and apply it to GCP and Azure instances as well
- TR = Time Reserved, the length of time the hardware is reserved for use by the software -- this would be the hours the instance was running. 
- EL = Expected Lifespan, the anticipated time that the equipment will be installed -- 4 years (average lifespan of servers) 
- RR = Resources Reserved, the number of resources reserved for use by the software -- number of vCPUs for that instance
- TR = Total Resources, the total number of resources available. -- total vCPUs possible in an instance family (bare metal instances) 

Rather than just using Teads' numbers though, let's generate our own numbers and compare.

**Comment by dtoakley** [comment]
As part of this spike, I have found that we are missing a number of AWS instances that exist in the Teads data set. You can see them in column A here: https://docs.google.com/spreadsheets/d/1XPHG0ta7Jlaawfr2bLS3Xj8xyLxqJskhmwVPiQygFM8/edit#gid=224728652

I've created [this](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/553) issue to address this.

**Comment by dtoakley** [comment]
Okay, I think I have enough information for the SPIKE on this for us to implement it now. Each Cloud provider will have their own data set, which will be used to determine a "Total Platform Embodied Emissions" using the same approach as Teads:
- AWS: we will just use Tead's data set for this
- GCP: we can calculate with the same approach 
- Azure: we can calculate with the same approach

I've done GCP [here](https://docs.google.com/spreadsheets/d/1YhtGO_UU9Hc162m7eQKYFQOnV4_yEK5_lgHYfl02JPE/edit#gid=725673372), and Azure is partially done as well -- needs a bit more data mining/formating. 

I would like to verify the following assumptions, but I think we can be unblocked from implementing a v1 for this now:
- When we don't know the specific platform, is it  okay to use largest vCPUs and Memory for Platform vCPUs and memory for the platform vCPUs and memory (e.g. GCP)?
- When we don't know how many SSD drive are provisioned, can we assume 1?
- Is it okay to assume platform sockets = 2 when we don't know the platorm type (e.g. Google) 
- Is it a single socket for AMD EPYC 3rd Gen?
- Is it dual sockets for Sandy Bridge and Ivy Bridge?

**Comment by dtoakley** [comment]
I also noticed in this spike that we are missing a number of latest generation Azure instance, as well as the Ice Lake Microarchitecture that is now used by GCP N2 machine types -- we should create new tickets for adding those.

**Comment by dtoakley** [comment]
Based on the data in the previous spreadsheet I have create this fresh [spreadsheet](https://docs.google.com/spreadsheets/d/1k-6JtneEu4E9pXQ9QMCXAfyntNJl8MnV2YzO4aKHh-0/edit#gid=0) with the final embodied emissions constants for each cloud provider - this should make implementation a lot easier.
