### ISSUE TITLE
Improve mock data for demo app

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#532]
**Context**
To make Cloud Carbon Footprint more quickly understood and more accessible to people who are less technical, we have built out a demo version of the app that uses mock data. Unfortunately there are some issues with this mock data that we would like to clean up. Feel free to do those that you're able to and comment if you can't fix all these issues.

**Improvements**
- [ ] Carbon, energy and cost data on timeline should show more of a correlation
- [ ] When data is grouped by day, the timeline chart should be smoother and more manageable to look at
- [ ] When I filter out data on the recommendations page, the forecast should never be negative (for example, unchecking AWS results in a negative cost for the 30 day forecast - see screenshot)
- [ ] When I view the cost and carbon demo data on the emissions dashboard, the amounts should make sense relative to each other
- [ ] When I view the cost and carbon demo data on the recommendations dashboard, the amounts should make sense relative to each other
- [ ] When I view the carbon and energy demo data on the emissions dashboard, the amounts should make sense relative to each other
- [ ] When I view the carbon and energy demo data on the recommendations dashboard, the amounts should make sense relative to each other

**Out of Scope**
- [ ] Modifying the dates of the mocked data, as that is covered in https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/745

<img width="1743" alt="Screen Shot 2021-11-05 at 3 39 32 PM" src="https://user-images.githubusercontent.com/8618241/140569573-0bd61232-1cb7-4249-85f5-835a04ec40e4.png">

**Comment by Samridhi-98** [comment]
Hey @4upz, I would like to work on this. Is this still open? 
If Yes, Can you just guide me where to start?

**Comment by 4upz** [comment]
Hey @Samridhi-98 yes! This issue is still open. The task may be a bit of a chore, but it mostly centers around providing bettermock data for the demo app's dashboard to be closer to what real data would look like. The numbers are a bit random, as they were generated using [mockaroo](https://www.mockaroo.com/). For instance, the line graph on demo.cloudcarbonfootprint.org is scattered and doesn't match the cost/emissions pattern you would see in a real graph (line chart for actual data pasted below for reference). We host the the mock recommendations, emissions, and footprint data in the `packages/client/stub-server/mockData.json`. So essentially, you would start there as we would need to go in and update the numbers to reflect a more realistic consistency. 

This also includes the cost and carbon savings for recommendations, as the forecast component sometimes will appear negative when filtering data due to the inconsistent numbers. It may be helpful if you have access to some form of real data to model the mock data after. The approach is pretty open-ended, and can be done programmatically (using a script or tool) or manually (which will be tedious). Hopefully that makes sense and is helpful! Feel free to let me know if you have any questions!

**Comment by Samridhi-98** [comment]
> Hey @Samridhi-98 yes! This issue is still open. The task may be a bit of a chore, but it mostly centers around providing bettermock data for the demo app's dashboard to be closer to what real data would look like. The numbers are a bit random, as they were generated using [mockaroo](https://www.mockaroo.com/). For instance, the line graph on demo.cloudcarbonfootprint.org is scattered and doesn't match the cost/emissions pattern you would see in a real graph (line chart for actual data pasted below for reference). We host the the mock recommendations, emissions, and footprint data in the `packages/client/stub-server/mockData.json`. So essentially, you would start there as we would need to go in and update the numbers to reflect a more realistic consistency.
> 
> This also includes the cost and carbon savings for recommendations, as the forecast component sometimes will appear negative when filtering data due to the inconsistent numbers. It may be helpful if you have access to some form of real data to model the mock data after. The approach is pretty open-ended, and can be done programmatically (using a script or tool) or manually (which will be tedious). Hopefully that makes sense and is helpful! Feel free to let me know if you have any questions!

Yeah, thanks for giving context. Also, do I need to create separate PR for each checklist item or one would be fine?

**Comment by 4upz** [comment]
@Samridhi-98 Yup! A single PR is fine

**Comment by Samridhi-98** [comment]
Hey @4upz, how can I test the changes the in `packages/client/stub-server/mockData.json` as there is no data or graph while running locally.

![image](https://user-images.githubusercontent.com/54466041/215256541-a5c525f1-009a-4d61-87d2-314b7f06c9b7.png)

![image](https://user-images.githubusercontent.com/54466041/215256307-d829a75f-66c9-4fba-9daa-25f2b68494fe.png)

**Comment by Samridhi-98** [comment]
Hey @4upz, I am thinking to write script for `mockdata.json` rather than going with manual update approach but, kinda confuse so need some insights. 

- For recommendations -
```
    {
      "cloudProvider": "AWS",
      "accountId": "aws account 0",
      "accountName": "aws account 0",
      "region": "us-west-1",
      "recommendationType": "Modify",
      "instanceName": "example-instance-5",
      "recommendationDetail": "Modify instance: example-instance-5.",
      "resourceId": "i-0f12345678912b12I",
      "kilowattHourSavings": 116.513,
      "costSavings": 3.611,
      "co2eSavings": 11.492
    }
```
Here we only need to update `kilowattHourSavings`, `costSavings`, `co2eSavings` ?
- I am not able to figure out the values that seems more realistics can you provide some real value stats where I can look into.

**Comment by 4upz** [comment]
Hey @Samridhi-98 that sounds like a great idea as a script would also be reusable and can be tweaked to further update the data in the future (and save you from manual labor 😄 ). To answer your questions: 

- Yes, only the `kilowattHourSavings` and `co2eSavings` need to be updated. The `costSavings` could be updated as well, but has the least amount of impact in terms of realism (as this can usually vary due to cost reductions, discounts, etc)
- I can provide you an example of a day's worth of real data since you're with Thoughtworks, but I would have to send it through internal channels due to the sensitivity of the data. Alternatively, the main discrepancy with the data is that the kilowatt hours and co2e don't correlate. These are the parts of the data that currently aren't realistic since energy usage should correlate (based on a coefficient) and match with the carbon emissions. I would recommend using the current kilowatt hours for each mock estimate but writing a script that uses the emissions factors (ex: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/gcp/src/domain/GcpFootprintEstimationConstants.ts#L183) and the region for that estimate to generate a more accurate co2e value that's more in line with the energy usage. 

Let me know if that makes sense! Happy to connect with you internally and share example data with you.

**Comment by Samridhi-98** [comment]
> Hey @Samridhi-98 that sounds like a great idea as a script would also be reusable and can be tweaked to further update the data in the future (and save you from manual labor 😄 ). To answer your questions:
> 
> * Yes, only the `kilowattHourSavings` and `co2eSavings` need to be updated. The `costSavings` could be updated as well, but has the least amount of impact in terms of realism (as this can usually vary due to cost reductions, discounts, etc)
> * I can provide you an example of a day's worth of real data since you're with Thoughtworks, but I would have to send it through internal channels due to the sensitivity of the data. Alternatively, the main discrepancy with the data is that the kilowatt hours and co2e don't correlate. These are the parts of the data that currently aren't realistic since energy usage should correlate (based on a coefficient) and match with the carbon emissions. I would recommend using the current kilowatt hours for each mock estimate but writing a script that uses the emissions factors (ex: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/gcp/src/domain/GcpFootprintEstimationConstants.ts#L183) and the region for that estimate to generate a more accurate co2e value that's more in line with the energy usage.
> 
> Let me know if that makes sense! Happy to connect with you internally and share example data with you.

Yeah sure, let me know when we can connect, I'll ask all my doubt as well 😅
