### ISSUE TITLE
Can we add 'line_item_resource_id' in the querry string so that we can get the id of resource to integrate with our application

### ISSUE THREAD

**Issue by SherryDongCN** [cloud-carbon-footprint/cloud-carbon-footprint#558]
## Feature Suggestion
**Is your feature request related to a problem? Please describe.**
I would like to enable our application to have the ability to add the energy estimation for each cloud resource, which is uniquely identified by its ARN Id, we already store some other resource info customers care about, we need to match the cloud resource entity in our system and the resource entity from the API in order to to empower our application to show energy estimation and suggestion.

**Describe the solution you'd like**
1.add the 'line_item_resource_id' in the query string
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/aws/src/lib/CostAndUsageReports.ts#L510
2. return the line_item_resource_id in the api 
 api/footprint?start=2021-05-02&end=2021-11-02

**Comment by dtoakley** [comment]
Hi @SherryDongCN -- thanks for raising this issue, it's a good use case we'd love to help support. My only concern with supporting this _by default_ is that it could significantly increase the number of rows returned by the Athena query and cause some performance problems. This is because we would want to add the column in the SELECT statement, but also add it to the GROUP BY in order to get all unique combinations of resource Ids. 

I tested this with internal Thoughtworks data via the console looking at the CUR data from 2021 grouped by month, and adding this new column increased the amount of data returned by ~25x. That being said, we'd love to get your feedback on that, and it's possible performance issues might not be a problem for your use case... 

To help you try it out, I've pushed the branch `resource-id-in-cur` with a proof of concept for adding this support. Would you be able to pull that branch and give it a go on your side and let us know it is behaving as you expect, and let us know how performance is?

**Comment by mattcui** [comment]
Hi @dtoakley , thank you very much for your commit, actually, we have cost and usage data (resource basis) from our own scan tool, so we don't need CCF to scan the data from the cloud provider, but we need CCF to help calculate the CO2e for each resource. So we would like to use CreateLookupTable approach to get the CO2e of each resource. In output.csv, we need resource_id column, I made a commit to show the resource_id in output.csv in my forked repo -> https://github.com/mattcui/cloud-carbon-footprint/commit/c054d69644bbe5d671cd9cfc621f7948119839bd. With your commit and mine, I can get the output.csv for resource basis. About the performance,  my input.csv is around 12M, and output is around 15M, it took around 20 seconds to get output on my Mac. Do you think if it acceptable, CCF could accept your and my commits? Thanks.

**Comment by mattcui** [comment]
Hi @dtoakley , actually, I found my commit is already enough for createLookupTable  approach to get resource level emission, so my commit doesn't need to rely on yours, do you think if my commit  can be acceptable by CCF? Thanks.

**Comment by dtoakley** [comment]
Hey @mattcui -- could I ask you to create a Pull Request for you commit and link it to this issue, so we can review it? Thank you!

**Comment by 4upz** [comment]
Hey there! Closing this issue since it seems the conversation has gone stale. We have added support for AWS tags to be used in CCF. Let us know if this fits your use case @SherryDongCN. And @mattcui if you'd still like to contribute this feature (or expand on the tags), feel free to still open a PR like suggested
