### ISSUE TITLE
[SPIKE] Look into calculating unknown emissions by the usage amount rather than the cost

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#562]
Currently, we are calculating unknown emissions creating a new Co2e/Cost coefficient by totaling both the cost and co2e per classification (Compute, Storage, Networking or Memory) and getting a Co2e per Cost ratios for each classification. We then reclassify each unknown usage row based on its pricing unit and usage type (ex reclassifying it as Compute). We then multiply the respective ratio by the cost associated with each reclassified unknown usage row to get an approximate carbon estimation.

We think we might be able to get more accurate results if instead of cost, we used the usage amount associated with each usage row. This would be essentially the same implementation but the ratios would instead be co2e per usage amount and those ratios would then be multiplied by each usage rows usage amount rather than cost.

We can start by creating new tabs in the existing spreadsheets and analyzing the difference in the data. If we feel comfortable with this approach, we could create an implementation ticket to update the code base.

Note: make sure you are looking at the usageType and usageUnit 

**A/C's**
- [x] Document calculation method as it will be needed to write up blurb for microsite

**Comment by dtoakley** [comment]
Changes pushed, QA tested locally and looks good. Closing this off.

**Comment by dtoakley** [comment]
After analyzing this approach for all three cloud providers, this should be the new algorithm for handling Unknown usage types:


1. For known usage types, track usageAmount and kilowatt Hour per service and usage unit:

```
{
appEngine: {
seconds: {
usageAmount: 10,
kilowattHours: 100,
}, {
bytes: {
usageAmont: 20,
kilowattHours: 200,
}, {
computeEngine: {...},
totals: {
seconds: {...},
bytes: {...},
totals: {...}
}
```
2. For unknown rows, if there is a known ratio with the same service and usage unit, multiple the usageAmount by the ratio
3. If there is no same service and usageUnit, then multiple the usageAmount by KwH/usageUnit ratio for all known usage (total)

GCP specific notes: 
- For usage unit "requests", multiple the usageAmount by the total kilowattHour per usageUnit for all units
- For the services "Secret Manager" and "Cloud Key Management Service (KMS)", also multiple the usageAmount by the total kilowattHour per usageUnit for all units

AWS specific notes: 
- We should continue to use Cost instead of usageAmount as a proxy, because there is no usage unit for AWS, only "pricing unit". Because of this Cost is a more accurate denominator to use 

Azure specific notes:
- Given the large permutations of usage units, we should normalize them before classifying the unknown usage. E.g. "10 hours" and "100 hours" become "hours".
