### ISSUE TITLE
GCP Embodied Emissions

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#578]
**Context**
We would like to comply with the SCI standard, and to do so, we will implement embodied emissions for each cloud provider.

**Related Issues**
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/524

**A/C's**
- [x] GCP embodied emissions should be included in compute estimates
- [ ] (After QA) Update Methodology to explain the inclusion of embodied emissions, the calculation, include public spreadsheet, and any GCP specific knowledge

**Tech Tasks**
- [x] Include total embodied emissions mapping to instance type (family) in GCP package
- [x] TR will be usage time period (group by)
- [x] EL may be constant in core package? Maybe you can change this given the cloud provider - possibly put in GCP cloud constants eg. serverExpectedLifespan
- [x] RR will be # of vCPUs, which we have
- [x] TR will be vCPUs over largest instance of that family
- [x] Will need new EmbodiedEmissionsEstimator class in core package to determine M using https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/dev/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md#embodied-emissions-m formula: M = TE * (TR/EL) * (RR/TR)
- [x] Can use estimator inside BillingExportTable class to estimate embodied emissions when the usage row includes a machine type that is in the list in the [spreadsheet](https://docs.google.com/spreadsheets/d/1k-6JtneEu4E9pXQ9QMCXAfyntNJl8MnV2YzO4aKHh-0/edit#gid=0)
- [x] Update coefficients to be correct
- [x] Add tests

**Comment by dtoakley** [comment]
Reviewed/QA'd, and this is looking good. I made two additional commits to get the approach more accurate:
1. [Updated](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/e90153910b67d47122063f187572d1e88238fe2b) the largest instance vCPU for Shared-core instances, to use the equivalent family 
2. [Updated](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/22f7ba7471a9b782552a7cdf7517c09a6b1b2d33) the GCP Embodied Emissions coefficients to be correct, due to my previous error in the calculations. 

I think we're good to document this in on the microsite now, for GCP - or separate that out into it's own documentation ticket to do all thre providers at once, when we publish next.
