### ISSUE TITLE
Add support for additional Azure regions

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#592]
## Context
seeking contributor
#### Overview
Adding support for Azure regions is not extremely straightforward. In different places, the naming of these regions is not exactly the same or predictable, so initially our team has only been able to add support for regions we are currently using. We would appreciate the addition of any regions not yet supported that you are using.

## Acceptance Criteria
- [ ] When I have usage in a previously unsupported Azure region, I now see the data for that region added to the total data for my Azure usage
- [ ] When I have usage in a previously unsupported Azure region, I now see my usage for that region within the bar chart, with the appropriate label, percentage of usage, color for grid intensity
- [ ] When I have usage in a previously unsupported Azure region, I now see that region in the region bar chart with a hover that has the region name and cloud provider, and total co2e for this region
- [ ] When I reference a new Azure region, I should follow the existing naming conventions
- [ ] When I have usage for a previously unsupported region that I can see this region in the region map and it's grid intensity is listed in the methodology on the microsite (Please reach out to the Green Cloud team if these two need to be completed - we will handle it.)

## Tech Tasks
- [ ] Changes to be made in packages/azure/src/lib/AzureRegions.ts
- [ ] Add appropriate test coverage, including edge cases.
- [ ] Run Changesets, bump any packages that have been updated/changed
- [ ] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.
- [ ] If any create-app templates have been updated, make sure to run the [test-create-app script](https://docs.google.com/document/d/1Ei6Cb2DjwEJUNtpULJSxbOuIdAfCARERgE3BSsKWrsc/edit) to ensure it still works properly.

## Review Tasks
- [ ] eg. specific QA details, update methodology, or update microsite

**Comment by ab-smith** [comment]
I'd like to help since I'm interested in trying this on Azure subscriptions with resources in France regions. If someone can point to the right direction/materials, I'll take it from there

**Comment by 4upz-tw** [comment]
Hi @ab-smith , sorry for the delayed response and thanks for volunteering to help with this issue! It would be awesome to have support for France regions! A good starting place for adding support for the regions are to begin with the [AzureRegions.ts](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/azure/src/lib/AzureRegions.ts) file. The ConsumptionManagement API from Azure often returns inconsistent strings for the region, so you will have to add the official name along with possible aliases from the API that you know of -- you can follow the other listed regions for the appropriate pattern. A good way to discover the aliases is to see what you're able to receive from the API after connecting your Azure credentials with subscriptions that include those regions to the CCF app. Our app should return the list of the regions you have that are unsupported. 

Afterwards, we may need to map an emissions factor for that region if we don't have one already in the [AzureFootprintEstimationConstants.ts](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/azure/src/domain/AzureFootprintEstimationConstants.ts) file for the `AZURE_EMISSIONS_FACTORS_METRIC_TON_PER_KWH` constant. We have a list of these emissions factors and their sources in the [Azure](https://www.cloudcarbonfootprint.org/docs/methodology#azure-2) section of our methodology which we usually get from the EPA or carboonfootprint.com. You're welcome to explore these sources to map the appropriate Emissions Factors for the region, otherwise feel free to make the PR with the added regions in the `AzureRegions.ts` file and we can verify and add the emissions factors before merging. 

Thank again! Also, don't hesitate to reach out if you have any questions or need additional support!

**Comment by LvffY** [comment]
Hi @ab-smith 

This seems to be an issue for my team too (See #401)

Did you have the chance to get into this point ?

**Comment by ab-smith** [comment]
Hi, unfortunately no, I had to postpone this for now.

**Comment by LvffY** [comment]
@4upz-tw @ericksod I'd like to contribute to this issue, but I'm not used to webapp development and API usage. Is there any command that you could share to detect which values to put in [AzureRegions](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/azure/src/lib/AzureRegions.ts) or [AzureFootprintEstimationConstants.ts](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/azure/src/domain/AzureFootprintEstimationConstants.ts) ? 

I'm able to make any manual API calls to Azure API (through python and bash mostly)
