### ISSUE TITLE
GCP Recommenders and update with ones we should support

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#693]
**Context**
We should consider including additional GCP recommenders and update ones we support.

For example, the [`Unattended Project recommender`](https://cloud.google.com/recommender/docs/unattended-project-recommender)

**A/C's**
- [x] Investigate additional available GCP recommenders
- [x] Understand data format/info we might get in response and how that might fit into our existing API and UI table structure
- [x] Spike as needed or pull out additional tickets

**Comment by dtoakley** [comment]
After digging into this, it seems there is nothing to implement right now. The recommendations fall in three categories:
1. We can't get the permissions to use the recommendation type, because it's very new - we have reached out to Google about this
2. We have no recommendations for a given type
3. We have recommendations, but they don't relate to any cost/carbon savings. E.g. `We recommend confirming the ownership of this project because it has considerable activity but no active owner during the observation period.`

**Comment by dtoakley** [comment]
The recommendations that fall in #1, so could be implemented once we have access are:
- [Cloud Run recommender](https://cloud.google.com/run/docs/recommender)
- [Google Maps Platform project management recommender](https://cloud.google.com/recommender/docs/gmp-project-management-recommender)

The recommendations that fall in #2, so could be implemented if we get some of those recommendations are:
- [Cloud SQL idle instance recommender](https://cloud.google.com/sql/docs/mysql/recommender-sql-idle)
- [Cloud SQL overprovisioned instance recommender](https://cloud.google.com/sql/docs/mysql/recommender-sql-overprovisioned)

The recommendations that fall in #3 are:
- [Unattended project recommender](https://cloud.google.com/recommender/docs/unattended-project-recommender)

Source: https://cloud.google.com/recommender/docs/recommenders
