### ISSUE TITLE
Implement Initial On-Prem Estimations

### ISSUE THREAD

**Issue by ccasher** [cloud-carbon-footprint/cloud-carbon-footprint#710]
#### Overview
Based on the spike work, we are ready to implement an initial flow for estimating on-prem estimations for compute and memory categories. This will entail providing a specific data-model for consumers to upload a csv file with the necessary data. CCF will read from the CSV and output on-prem estimates to a new CSV using a CLI command.

## Acceptance Criteria
- [ ] When I run `yarn run estimate-on-premise-data` from the cli package and provide the input csv with `--onPremiseInput` located in the cli package root directory and optional output file name with `--onPremiseOutput`, then a new csv file should be generated with the energy and emissions appended to each row.

## Tech Tasks
- [x] Create a new on-prem package with a similar directory structure to azure
- [x] Within the src/application directory, create a new file OnPrem.ts where a new OnPrem class lives
- [x] Create a method in the OnPrem class called getDataForOnPrem that instantiates a new OnPremDataReport class which will live in OnPremDataReport.ts in src/lib, that takes in the compute and memory estimators and calls a getEstimates method
- [x] Handle the follow columns:
        cpuId: string
        memory: number,
        machineType: string,
        startTime: timestamp string,
        endTime: timestamp string,
        country?: string,
        region?: string,
        serverUtilization?: number,
        pue?: number
- [x] Write the getEstimates class to map through the rows and use a switch statement by machine type to add a case for  servers that then grab the necessary information to send to the estimators and return the estimates objects
- [x] Add method to transform the timestamps to usage hours
- [x] Add method to parse cpuId to grab processor id
- [x] In src/domain, add a file called OnPremFootprintEstimateConstants.ts and add the respective constants for coefficients, PUE average, server utilization average, memory, min and max watts for each processor family, and emissions factors
- [x] In src/lib, create a file called OnPremDataReportRow.ts that contains a new class to define constants and necessary methods from each usage row
- [x] In src/lib, create a new file called MachineTypes.ts that will contains all of the processor family maps
- [x] Add a new cli command in the cli package that calls a new method in App.ts that instantiates a new OnPrem class and calls the method to get estimates
- [x] Add appropriate test coverage, including edge cases using TDD.
- [ ] Run Changesets, bump any packages that have been updated/changed
- [ ] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.
- [ ] If any create-app templates have been updated, make sure to run the [test-create-app script](https://docs.google.com/document/d/1Ei6Cb2DjwEJUNtpULJSxbOuIdAfCARERgE3BSsKWrsc/edit) to ensure it still works properly.

## Review Tasks
- [ ] eg. specific QA details, update methodology, or update microsite

**Comment by dtoakley** [comment]
Have review this and it's looking pretty good! Here's my feedback:

- @google-cloud/secret-manager should be removed from the production dependancies - dev dependancies are fine though 
- Jest coverage thresholds should be increase to match the actual coverage, e.g. 99% for statements 
- I'm thinking we we should rename `cpuId` to `serverName` or `processorName` - because we will want to support GPUs at some point, and right now they wouldn't match that model name 
- Update input data to require emory to be in Gigabytes 
- Add a comment in the `ON_PREMISE_EMISSIONS_FACTORS_METRIC_TON_PER_KWH` to explain that the US states are actually NERC region emissions factors
- Add a ADR for this, including the change to the compute estimation function with optional `averageWatts` and why this is good from a user perspective  
- Add column to read and write cost 

Other than that, everything looks great!
