### ISSUE TITLE
How to set external carbon footprint api to carbon-footprint-client

### ISSUE THREAD

**Issue by rafaelsilvaaaaa10** [cloud-carbon-footprint/cloud-carbon-footprint#731]
Hello,

I'm trying to run the environment in docker (kubernetes), however the frontend keeps trying to look for the endpoint (localhost:4000).

So now we have a new endpoint which is my-endpoint:80. How do I change from localhost:4000 to my-endpoint:80? Is there an env for this? I looked in the code and didn't find it.

Thank you for your help.

**Comment by 4upz-tw** [comment]
Hi @rafaelsilvaaaaa10 
Thanks for reaching out. For a quick fix, you can update each axios call being made to the api in the `packages/client/src/utils/hooks` folder. The URL being passed in the axios call is using a relative path as default which is making it use the localhost:4000/api/ endpoint as automatically provided by create-react-app. You can change this URL to be an absolute path such as `axios.get('my-endpoint:80/api/footprint/, ...)`. This will need to be done in each call being made in the `RemoteServiceHook.ts` (line 35), `EmissionFactorServiceHook.ts` (line 26), and the `RecommendationServiceHook.ts` (lines 26 and 31) files within that folder.

However, a better solution would be to pass in a client side environment variable as the Base URL to use. If you're interested in contributing this, let us know and we can create a ticket for it and point you in the right direction. Otherwise, I'll be closing this issue but feel free to reopen it if that solution doesn't work for you and if you need additional assistance!
