### ISSUE TITLE
Command to fill cache files

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#738]
**Context:**
When using CCF for organizations with a lot of cloud usage, it is often slow to initially query and retrieve the cloud provider billing data. In order to improve this experience, we would like to create a command that can be run prior to spinning up the app that will gather this data and fill the cache file. This way, you can load the data ahead of time in the background, and not have the app time out.

**Out of scope**
- [ ] When passing a group by, existing behavior should stand (a new cache file is created for each group by if not yet populated)

**A/C's:**
- [x] Given I have an empty cache file and I run the command `seed-cache-file` in the command line, I can see that the cache file has been populated with my data.
- [x] Given I have run the command `seed-cache-file`, I receive a message indicating it is pulling my data, and a message when it has successfully completed indicating which cache file my data is loaded into. Can look into OS alerts
- [x] Given I have a populated cache file from a few days ago, when I run the command `seed-cache-file`, I can see any missing data has appended 
- [x] Given I have a populated cache file with missing days (eg I have recently had AWS backfill my data), and I run the command `seed-cache-file`, I can now see data from the missing days
- [x] Given I run the command `seed-cache-file` and there is an error (eg connecting to cloud provider, timing out), I see a message in the terminal indicating this and suggesting how I may resolve the issue
- [x] Given I enter the command `seed-cache-file` I am prompted to enter start date, end date, and groupBy
- [ ] Given I am looking at the documentation, I can see a description of this option TBD where

**Comment by drscarbrotw** [comment]
I'll take this card. Looks like a fun one. 🥳 😹

**Comment by drscarbrotw** [comment]
refactored implementation and tests for interactive prompts. submitted pr for review and feedback.

**Comment by drscarbrotw** [comment]
Researching alerts from command prompt.

We can use native scripting to create system alerts without additional imports.
The implementation uses the spawn method from the process package in order to create/spawn a new process that calls the native or an installed scripting environment: osascript, powershell, cscript, wscript, whiptail, xmessage, yad, etc.

Most npm notification packages leverage a visual basic script file for windows. The packages typically switch on OS name and then select the correct scripting environment and script.

The alert npm package provides a very simple implementation. Others provide a more complex implementation in order to facilitate additional styling, etc.

I've linked refs below.

Because each OS or user may have scripting 

Examples:
https://github.com/zacanger/alert
https://github.com/s-h-a-d-o-w/node-native-dialog

IOS Script:
const { spawn } = require('child_process')
const { platform } = process

const execCmd = (cmds) => spawn(cmds[0], cmds.splice(1))
const osascript = (message) => [
    'osascript',
    '-e',
    `tell app "System Events" to display dialog "${ message }" buttons "OK"`, ,
]

const powerShell = (message) => [
    'powershell.exe',
]

function popUp(message) {
    switch (platform) {
        case 'darwin':
            execCmd(osascript( message ))
    }
}

module.exports = { popUp }
