### ISSUE TITLE
Deploying to Azure

### ISSUE THREAD

**Issue by ghost** [cloud-carbon-footprint/cloud-carbon-footprint#814]
looking out for help on how to deploy this solution to azure instead of running locally..

thanks
Phani

**Comment by 4upz-tw** [comment]
Hi Phani (@koundi24)! Unfortunately, we don't have a tested solution for deploying to Azure at the moment! However, we're open to contributions for steps or a solution so that we can include it on our [Deploying](https://www.cloudcarbonfootprint.org/docs/deploying) page.

In the meantime, feel free to check out that same page for alternative steps on how to deploy on AWS or Google App Engine. Perhaps they may provide some insight on similar services for use in deploying to Azure.
