### ISSUE TITLE
Backfilling cache should also backfill cloud providers

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#824]
Currently we backfill missing dates but not amend dates to include eg a cloud provider that has been added since

- recognize if discrepancy with data
- need to define the criteria "to be different"
- if you change the configuration, should mark the cache as invalid
- if new cloud provider, would ideally want to **append** the data - can do this more easily by looking at age of data (mongo db will help with this)

In order to accomplish this, we will need a mechanism for identifying if there are missing cloud providers from a given day

**Comment by 4upz** [comment]
Implementation looks good, just needs the following fixes/additions:

- Adding documentation and .env.template note for `INCLUDE_ESTIMATES` config variable
- Fixing `INCLUDE_ESTIMATES` config vars for each cloud provider defaulting to `true` instead of `false`
- Potentially investigate timestamp error when fetching emissions

**Comment by 4upz** [comment]
Process also seems to hang after seeding cache file. May have been previous behavior, but would be good to exit (without hitting ctrl + c) when finished

**Comment by 4upz** [comment]
Not sure if a big deal, but validation error also occurs if not providing uppercase version of cloud provider. May be good to convert to uppercase during validation (for better user experience) or to have the lowercase inputs be the expected answer and then capitalizing later on (to be consistent with grouping methods)
