### ISSUE TITLE
Cannot install dependencies for fresh clone repo. Encounter a checksum error.

### ISSUE THREAD

**Issue by chrisza-tw** [cloud-carbon-footprint/cloud-carbon-footprint#855]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:** Mac OS Monterey 12.3
- **Yarn version**: 3.1.1
- NodeJs: 17.7.1

### Expected Behavior

After I clone the repo and install dependencies using `yarn`, the dependencies should be successfully installed.

### Actual Behavior

There is a checksum error while install dependencies in package `remark-license`.

```
➜  cloud-carbon-footprint git:(trunk) yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @cloud-carbon-footprint/client@workspace:packages/client doesn't provide @mui/system (p634cd), requested by @mui/x-data-grid
➤ YN0060: │ @cloud-carbon-footprint/client@workspace:packages/client provides react (p81d5a) with version 17.0.2, which doesn't satisfy what react-dates and some of its descendants request
➤ YN0060: │ @cloud-carbon-footprint/client@workspace:packages/client provides react-dom (pf11c5) with version 17.0.2, which doesn't satisfy what react-dates and some of its descendants request
➤ YN0002: │ @cloud-carbon-footprint/create-app@workspace:packages/create-app doesn't provide @types/node (p1b472), requested by ts-node
➤ YN0002: │ @cloud-carbon-footprint/create-app@workspace:packages/create-app doesn't provide prettier (pce2c2), requested by eslint-plugin-prettier
➤ YN0002: │ @cloud-carbon-footprint/integration-tests@workspace:packages/integration-tests doesn't provide @babel/core (pe0805), requested by @babel/eslint-parser
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [896c2] doesn't provide @babel/plugin-syntax-flow (p648c1), requested by eslint-plugin-flowtype
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [896c2] doesn't provide @babel/plugin-transform-react-jsx (pcecbf), requested by eslint-plugin-flowtype
➤ YN0002: │ react-dev-utils@npm:12.0.1 doesn't provide typescript (p59348), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-dev-utils@npm:12.0.1 doesn't provide webpack (p1012e), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ root@workspace:. doesn't provide @types/node (p23cb6), requested by ts-node
➤ YN0002: │ testcafe-reporter-dashboard@npm:1.0.0-rc.1 doesn't provide fp-ts (pe5446), requested by io-ts-types
➤ YN0002: │ testcafe-reporter-dashboard@npm:1.0.0-rc.1 doesn't provide fp-ts (pe1a1d), requested by io-ts
➤ YN0002: │ testcafe-reporter-dashboard@npm:1.0.0-rc.1 doesn't provide fp-ts (p1dfe6), requested by monocle-ts
➤ YN0002: │ testcafe-reporter-dashboard@npm:1.0.0-rc.1 doesn't provide fp-ts (pc987e), requested by newtype-ts
➤ YN0002: │ ts-node-dev@npm:2.0.0 [88b31] doesn't provide @types/node (p1cab1), requested by ts-node
➤ YN0002: │ xo@npm:0.49.0 doesn't provide webpack (p35719), requested by eslint-import-resolver-webpack
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ remark-license@https://github.com/niftylettuce/remark-license.git#commit=17ecb8f64f8f6082414d14f9267a12764e6ddbfb can't be found in the ca
➤ YN0013: │ remark-license@https://github.com/niftylettuce/remark-license.git#commit=17ecb8f64f8f6082414d14f9267a12764e6ddbfb can't be found in the ca
➤ YN0018: │ remark-license@https://github.com/niftylettuce/remark-license.git#commit=17ecb8f64f8f6082414d14f9267a12764e6ddbfb: The remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 3s 262ms
➤ YN0000: Failed with errors in 3s 406ms
```

### To Reproduce

1. Clone new repo
2. `yarn`

### Additional Information

For workaround:

```
YARN_CHECKSUM_BEHAVIOR=update yarn
```

But this going to update checksum in yarn.lock locally. 

I think it would be great if we can update checksum in this repo so the installation is smooth.

© 2021 Thoughtworks, Inc.

**Comment by 4upz** [comment]
Hi @chrisza-tw , thanks for checking out the tool! I saw your PR and I'm wondering if whether manually updating the repo is the right way to go since it tends to change pretty often. Unfortunately, I wasn't able to replicate the issue you were facing during a fresh clone and install of the repository with the same yarn and node versions. Have you instead tried running a command such as `yarn cache clean --all` and then retrying an install and seeing if that works?

**Comment by chrisza-tw** [comment]
Sadly, I still got same issues after `yarn cache clean --all`

https://user-images.githubusercontent.com/78129674/177934260-092a741f-6775-4ce8-979f-29889b617673.mp4

**Comment by 4upz** [comment]
Hmm, that's interesting -- especially since its only a peer dependency. I wonder if this is just a result of an outdated package. Sorry about that hassle, I'll look into merging in your PR as a quick fix and look into making sure that the remark-license's original dependency is properly updated. Let us know if you run into any other issues!

**Comment by 4upz** [comment]
Hey @chrisza-tw, just following up on this again after doing a PR review. I mentioned before that we initially weren't able to replicate the issue when doing a fresh clone and install with the current main branch. When using the changes with this PR, my teammate and I now get the same error you were facing before with the checksum -- which seems that it has the reverse effect on us 😅. Another suggestion before we explore this as a solution: Would you mind trying to delete the local `yarn.lock` and doing a `yarn install` so that it creates a new one?

Creating a fresh yarn.lock locally may be a better solution if the checksum change may mess up the installation for others. If that doesn't work, we may just need to delete the `yarn.lock` on our end and push up a new one to ensure that all the checksums are updated so that it's not out of sync for everyone.

I also see that you're a Thoughtworker, so I'm also happy to hop on a call and discuss further if you'd like!

**Comment by 4upz** [comment]
Sorry for the back to back messages, but we actually discovered the issue and just did the latter for you. Apparently we had some old peer dependencies in the yarn.lock that had been removed -- which included the `remark-license`. We just pushed an updated lock file. Would you mind pulling the changes and giving that another go instead?

**Comment by chrisza-tw** [comment]
@4upz The new lock file works for me. Thanks!

**Comment by 4upz** [comment]
Great! I'll go ahead and close this issue. Let us know if you have any other trouble! We also have other tasks that are open to contributors on our project board. Feel free to take a look and let us know if you'd like to contribute elsewhere. 😁
