### ISSUE TITLE
CLI does not report correct Azure data

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#906]
Only with CLI with branch "azure-subscription-chunks"
* Collect good Azure data
* Can't collect AWS data
Only with CLI with branch "latest"
* Collect wrong Azure data
* Collect good AWS data

Consider bringing "azure-subscription-chunks" in as a way to get azure data

**Comment by 4upz** [comment]
Subscription chunks were created as an alternative to hopefully improve Azure performance. Therefore, I'm going to look at making the updates in https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/943 to see if that resolves most performance issues before implementing that workaround. That way we're not adding a new config/query method if it isn't needed

**Comment by 4upz** [comment]
As a reminder, this issue stemmed from this [discussion](https://groups.google.com/g/cloud-carbon-footprint/c/_wxI5LbKHSg/m/RcqCV6bnCgAJ) in the Google group. I was not able to replicate the inability to grab AWS data on the chunks branch vs the trunk branch. There are a difference in estimates, with the trunk branch having lower numbers on average. However, due to the time difference causing them to be at difference stages in the methodology, comparison of accuracy may not be the best route due to the differences in magnitude.

In the context of the ticket, the correctness of the estimates seem to be the proximity to Microsoft Power BI which also may not be the best route due to differences in methodology. I think the best thing to focus on this the ability of the trunk branch to get Azure estimates without rate limits and for estimates through the CLI to be able to give numbers for the following Azure services: Virtual Machines, SQL Database, Storage, Bandwidth, Azure App Service. I propose these for the next steps:
- In reference to the ability to get estimates for those services, I was able to get valid numbers for a single day's estimate of everything except Storage (received `NaN`). May be best to create a separate bug ticket that verifies and fix this.
- For rate limits, we are still at the mercy of the API even with prior improvements, but we can still allow workarounds such that the subscription chunks tried to accomplish for users to customize the synchronous or asynchronous method in which they grab data for Azure. This can probably be done in the following ways (through separate task issues):
  - Allow config option to fetch Azure data in chunks by subscription. This includes an option to enable the chunk method and to specify the chunk size to their liking.
  - Allow config option to fetch Azure data synchronously, with the caveat that this will take the longest but will encounter less rate issues. 
  - Allow config option to fetch Azure data by specific subscriptions/account by providing a list of desired subscriptions. Similar to chunks, but with higher specificity of what exact data to retrieve (instead of all data for the configured account)
  
Once a way forward is decided, I think all of the work that can be done for this specific issue is concluded and any subsequent tasks can link back to this one.

**Comment by 4upz** [comment]
Team has decided that both methods makes sense as next steps, so follow-up work for each task will be tracked in #1021 for Missing Services and #1022 for chunk enablement
