### ISSUE TITLE
Azure data collection keeps failing: Too many requests

### ISSUE THREAD

**Issue by ab-smith** [cloud-carbon-footprint/cloud-carbon-footprint#933]
Hello,
I don't know if it's specific to my azure subscription or something changed on Azure Rate limiting :

### Issue Details

- **Operating System:**
  - MacOS
- **Browser:**
  - Chrome

### Expected Behavior

Standard CCFP data

### Actual Behavior

It keeps looping for a very long time after which, it showed this message multiple times:

[1] 2022-10-16T14:35:20.203Z [ConsumptionManagement] info: Retrying after 60 seconds
[1] 2022-10-16T14:35:21.592Z [ConsumptionManagement] warn: Azure ConsumptionManagementClient.usageDetails.listNext failed. Reason: Too many requests. Please retry after 60 seconds.

### To Reproduce

- followed the step of creating an App and the associated credential for azure and done yarn install, yarn install-guided then yarn start

### Additional Information

- tried to tweak the Config.ts file to change the groupBy, force a startDate, etc. didn't seem to help.
- tested on trunk, hash e700bc76a0d8d27c01f30cf4d646e189cdd224b5, went back to other releases tags but got a lot of memory leaks.

Thank you

**Comment by ab-smith** [comment]
could be related to https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/902

**Comment by 4upz** [comment]
Hi @ab-smith thanks for bringing up this issue! This is a common problem that is encountered with large amount of Azure subscriptions due to Azure's rate limiting. The reason you are encountering the loop is because we have implemented a manual retry time in which our app tries to wait a certain amount of time before trying to query the subscriptions again in hopes that the rate timeout has lifted. While this should eventually get all of the estimates after a certain amount of times, we understand if this is not ideal or if you you want to try minimizing the logs. We're currently exploring optimization options, but you can try one of the following workarounds if you wish to minimize the retry and logs that you are seeing:

- Modifying the `AzureAccount.ts` file to specify a specific amount of subscriptions so that the amount of subscriptions queried our reduced to a few at a time. You can find a full description of how to do so in this Google Group message surrounding the same issue: https://groups.google.com/g/cloud-carbon-footprint/c/_wxI5LbKHSg/m/YHHWkiWeAgAJ
- In the same file, modifying the retry limit so that it tries more or less queries at a time in between the limits
- You can [seed your cache file](https://www.cloudcarbonfootprint.org/docs/data-persistence-and-caching#seeding-cache-file) `yarn seed-cache-file` to query and populate your cache with estimates in the background. This won't help the performance, but at least helps you run the process separately before attempting to use it in the client

Let us know if any of that helps, and keep an eye out for more details as we continue to improve our Azure approach.
