### ISSUE TITLE
Spike frameworks for API documentation

### ISSUE THREAD

**Issue by ericksod** [cloud-carbon-footprint/cloud-carbon-footprint#944]
Explore frameworks for API documentation

https://github.com/slatedocs/slate

**Comment by ghost** [comment]
After investigating slate, it turns out that it is not an annotation parsing and REST API documentation I thought it was. I was expecting something similar to swagger. 

## TSOA

https://tsoa-community.github.io/docs/

Is more in line with what I was thinking. It is simple to implement and leverages Swagger-UI to automatically create HTML for documentation and testing. The problem here is that it relies on decorators, such as `@Post`, `@Get` etc. And I discovered that decorators are not supported on function declarations according to their specs (https://github.com/microsoft/TypeScript/issues/2249). 

So, regardless of which framework we chose. If we want to rely on decorators to annotate our API we may have to refactor https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/fd4ec19b5b920aa7781d8b5d54889c75dadeaed0/packages/api/src/api.ts to use classes instead of functions to define our routes. 

### Alternative to decorators

It is possible to avoid the use of decorators if we are willing to write the specs by hand as defined by https://spec.openapis.org/oas/v3.1.0.html  

A working example for `swagger-ui` is pushed into `api-docs` branch although it has no information. We could draft the API documentation using https://editor.swagger.io/ but that would defeat the purpose of keeping the code and documentation in sync and close to each other.
