### ISSUE TITLE
Fix recommendations page in integration tests

### ISSUE THREAD

**Issue by camcash17** [cloud-carbon-footprint/cloud-carbon-footprint#959]
After recent changes to the API, the integration tests are failing on the recommendations page, where currently there are actual requests being sent to the cloud API's instead of using mock data.

**Comment by tinamthomas** [comment]
I looked into this a little bit since the tests were passing for me locally despite this issue.

From what I can see of the the code, it looks like there's a test mode in the app.ts file for recommendations, to ensure it sends mock data (See [here](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/app/src/App.ts#L158))

And the app that's started for the integration test seems to be setting the env variable correctly (See [here](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/integration-tests/package.json#L9))

----
UPDATE: 
The reason  they were passing for me but failing for others was because I do not have configurations for AWS/GCP/Azure set up.
